package com.uvcrawler.vo.client;

import com.uvcrawler.vo.Company;
import com.uvcrawler.vo.CompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	int countByExample(CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	int deleteByExample(CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	int insert(Company record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	int insertSelective(Company record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	List<Company> selectByExampleWithBLOBs(CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	List<Company> selectByExample(CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	Company selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Company record,
			@Param("example") CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	int updateByExampleWithBLOBs(@Param("record") Company record,
			@Param("example") CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	int updateByExample(@Param("record") Company record,
			@Param("example") CompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	int updateByPrimaryKeySelective(Company record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	int updateByPrimaryKeyWithBLOBs(Company record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	int updateByPrimaryKey(Company record);
}
