package com.uvcrawler.vo.client;

import com.uvcrawler.vo.Crawlinfolog;
import com.uvcrawler.vo.CrawlinfologExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrawlinfologMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_crawlinfolog
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	int countByExample(CrawlinfologExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_crawlinfolog
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	int deleteByExample(CrawlinfologExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_crawlinfolog
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_crawlinfolog
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	int insert(Crawlinfolog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_crawlinfolog
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	int insertSelective(Crawlinfolog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_crawlinfolog
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	List<Crawlinfolog> selectByExample(CrawlinfologExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_crawlinfolog
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	Crawlinfolog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_crawlinfolog
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Crawlinfolog record,
			@Param("example") CrawlinfologExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_crawlinfolog
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	int updateByExample(@Param("record") Crawlinfolog record,
			@Param("example") CrawlinfologExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_crawlinfolog
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	int updateByPrimaryKeySelective(Crawlinfolog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_crawlinfolog
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	int updateByPrimaryKey(Crawlinfolog record);
}
