package com.uvcrawler.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CompanyExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public CompanyExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andIndustryIsNull() {
			addCriterion("industry is null");
			return (Criteria) this;
		}

		public Criteria andIndustryIsNotNull() {
			addCriterion("industry is not null");
			return (Criteria) this;
		}

		public Criteria andIndustryEqualTo(String value) {
			addCriterion("industry =", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryNotEqualTo(String value) {
			addCriterion("industry <>", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryGreaterThan(String value) {
			addCriterion("industry >", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryGreaterThanOrEqualTo(String value) {
			addCriterion("industry >=", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryLessThan(String value) {
			addCriterion("industry <", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryLessThanOrEqualTo(String value) {
			addCriterion("industry <=", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryLike(String value) {
			addCriterion("industry like", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryNotLike(String value) {
			addCriterion("industry not like", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryIn(List<String> values) {
			addCriterion("industry in", values, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryNotIn(List<String> values) {
			addCriterion("industry not in", values, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryBetween(String value1, String value2) {
			addCriterion("industry between", value1, value2, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryNotBetween(String value1, String value2) {
			addCriterion("industry not between", value1, value2, "industry");
			return (Criteria) this;
		}

		public Criteria andProviceIsNull() {
			addCriterion("provice is null");
			return (Criteria) this;
		}

		public Criteria andProviceIsNotNull() {
			addCriterion("provice is not null");
			return (Criteria) this;
		}

		public Criteria andProviceEqualTo(String value) {
			addCriterion("provice =", value, "provice");
			return (Criteria) this;
		}

		public Criteria andProviceNotEqualTo(String value) {
			addCriterion("provice <>", value, "provice");
			return (Criteria) this;
		}

		public Criteria andProviceGreaterThan(String value) {
			addCriterion("provice >", value, "provice");
			return (Criteria) this;
		}

		public Criteria andProviceGreaterThanOrEqualTo(String value) {
			addCriterion("provice >=", value, "provice");
			return (Criteria) this;
		}

		public Criteria andProviceLessThan(String value) {
			addCriterion("provice <", value, "provice");
			return (Criteria) this;
		}

		public Criteria andProviceLessThanOrEqualTo(String value) {
			addCriterion("provice <=", value, "provice");
			return (Criteria) this;
		}

		public Criteria andProviceLike(String value) {
			addCriterion("provice like", value, "provice");
			return (Criteria) this;
		}

		public Criteria andProviceNotLike(String value) {
			addCriterion("provice not like", value, "provice");
			return (Criteria) this;
		}

		public Criteria andProviceIn(List<String> values) {
			addCriterion("provice in", values, "provice");
			return (Criteria) this;
		}

		public Criteria andProviceNotIn(List<String> values) {
			addCriterion("provice not in", values, "provice");
			return (Criteria) this;
		}

		public Criteria andProviceBetween(String value1, String value2) {
			addCriterion("provice between", value1, value2, "provice");
			return (Criteria) this;
		}

		public Criteria andProviceNotBetween(String value1, String value2) {
			addCriterion("provice not between", value1, value2, "provice");
			return (Criteria) this;
		}

		public Criteria andCityIsNull() {
			addCriterion("city is null");
			return (Criteria) this;
		}

		public Criteria andCityIsNotNull() {
			addCriterion("city is not null");
			return (Criteria) this;
		}

		public Criteria andCityEqualTo(String value) {
			addCriterion("city =", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotEqualTo(String value) {
			addCriterion("city <>", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThan(String value) {
			addCriterion("city >", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThanOrEqualTo(String value) {
			addCriterion("city >=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThan(String value) {
			addCriterion("city <", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThanOrEqualTo(String value) {
			addCriterion("city <=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLike(String value) {
			addCriterion("city like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotLike(String value) {
			addCriterion("city not like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityIn(List<String> values) {
			addCriterion("city in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotIn(List<String> values) {
			addCriterion("city not in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityBetween(String value1, String value2) {
			addCriterion("city between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotBetween(String value1, String value2) {
			addCriterion("city not between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andTownIsNull() {
			addCriterion("town is null");
			return (Criteria) this;
		}

		public Criteria andTownIsNotNull() {
			addCriterion("town is not null");
			return (Criteria) this;
		}

		public Criteria andTownEqualTo(String value) {
			addCriterion("town =", value, "town");
			return (Criteria) this;
		}

		public Criteria andTownNotEqualTo(String value) {
			addCriterion("town <>", value, "town");
			return (Criteria) this;
		}

		public Criteria andTownGreaterThan(String value) {
			addCriterion("town >", value, "town");
			return (Criteria) this;
		}

		public Criteria andTownGreaterThanOrEqualTo(String value) {
			addCriterion("town >=", value, "town");
			return (Criteria) this;
		}

		public Criteria andTownLessThan(String value) {
			addCriterion("town <", value, "town");
			return (Criteria) this;
		}

		public Criteria andTownLessThanOrEqualTo(String value) {
			addCriterion("town <=", value, "town");
			return (Criteria) this;
		}

		public Criteria andTownLike(String value) {
			addCriterion("town like", value, "town");
			return (Criteria) this;
		}

		public Criteria andTownNotLike(String value) {
			addCriterion("town not like", value, "town");
			return (Criteria) this;
		}

		public Criteria andTownIn(List<String> values) {
			addCriterion("town in", values, "town");
			return (Criteria) this;
		}

		public Criteria andTownNotIn(List<String> values) {
			addCriterion("town not in", values, "town");
			return (Criteria) this;
		}

		public Criteria andTownBetween(String value1, String value2) {
			addCriterion("town between", value1, value2, "town");
			return (Criteria) this;
		}

		public Criteria andTownNotBetween(String value1, String value2) {
			addCriterion("town not between", value1, value2, "town");
			return (Criteria) this;
		}

		public Criteria andLinkmanIsNull() {
			addCriterion("linkman is null");
			return (Criteria) this;
		}

		public Criteria andLinkmanIsNotNull() {
			addCriterion("linkman is not null");
			return (Criteria) this;
		}

		public Criteria andLinkmanEqualTo(String value) {
			addCriterion("linkman =", value, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanNotEqualTo(String value) {
			addCriterion("linkman <>", value, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanGreaterThan(String value) {
			addCriterion("linkman >", value, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanGreaterThanOrEqualTo(String value) {
			addCriterion("linkman >=", value, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanLessThan(String value) {
			addCriterion("linkman <", value, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanLessThanOrEqualTo(String value) {
			addCriterion("linkman <=", value, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanLike(String value) {
			addCriterion("linkman like", value, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanNotLike(String value) {
			addCriterion("linkman not like", value, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanIn(List<String> values) {
			addCriterion("linkman in", values, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanNotIn(List<String> values) {
			addCriterion("linkman not in", values, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanBetween(String value1, String value2) {
			addCriterion("linkman between", value1, value2, "linkman");
			return (Criteria) this;
		}

		public Criteria andLinkmanNotBetween(String value1, String value2) {
			addCriterion("linkman not between", value1, value2, "linkman");
			return (Criteria) this;
		}

		public Criteria andLegalPersionIsNull() {
			addCriterion("legal_persion is null");
			return (Criteria) this;
		}

		public Criteria andLegalPersionIsNotNull() {
			addCriterion("legal_persion is not null");
			return (Criteria) this;
		}

		public Criteria andLegalPersionEqualTo(String value) {
			addCriterion("legal_persion =", value, "legalPersion");
			return (Criteria) this;
		}

		public Criteria andLegalPersionNotEqualTo(String value) {
			addCriterion("legal_persion <>", value, "legalPersion");
			return (Criteria) this;
		}

		public Criteria andLegalPersionGreaterThan(String value) {
			addCriterion("legal_persion >", value, "legalPersion");
			return (Criteria) this;
		}

		public Criteria andLegalPersionGreaterThanOrEqualTo(String value) {
			addCriterion("legal_persion >=", value, "legalPersion");
			return (Criteria) this;
		}

		public Criteria andLegalPersionLessThan(String value) {
			addCriterion("legal_persion <", value, "legalPersion");
			return (Criteria) this;
		}

		public Criteria andLegalPersionLessThanOrEqualTo(String value) {
			addCriterion("legal_persion <=", value, "legalPersion");
			return (Criteria) this;
		}

		public Criteria andLegalPersionLike(String value) {
			addCriterion("legal_persion like", value, "legalPersion");
			return (Criteria) this;
		}

		public Criteria andLegalPersionNotLike(String value) {
			addCriterion("legal_persion not like", value, "legalPersion");
			return (Criteria) this;
		}

		public Criteria andLegalPersionIn(List<String> values) {
			addCriterion("legal_persion in", values, "legalPersion");
			return (Criteria) this;
		}

		public Criteria andLegalPersionNotIn(List<String> values) {
			addCriterion("legal_persion not in", values, "legalPersion");
			return (Criteria) this;
		}

		public Criteria andLegalPersionBetween(String value1, String value2) {
			addCriterion("legal_persion between", value1, value2,
					"legalPersion");
			return (Criteria) this;
		}

		public Criteria andLegalPersionNotBetween(String value1, String value2) {
			addCriterion("legal_persion not between", value1, value2,
					"legalPersion");
			return (Criteria) this;
		}

		public Criteria andMainProductsIsNull() {
			addCriterion("main_products is null");
			return (Criteria) this;
		}

		public Criteria andMainProductsIsNotNull() {
			addCriterion("main_products is not null");
			return (Criteria) this;
		}

		public Criteria andMainProductsEqualTo(String value) {
			addCriterion("main_products =", value, "mainProducts");
			return (Criteria) this;
		}

		public Criteria andMainProductsNotEqualTo(String value) {
			addCriterion("main_products <>", value, "mainProducts");
			return (Criteria) this;
		}

		public Criteria andMainProductsGreaterThan(String value) {
			addCriterion("main_products >", value, "mainProducts");
			return (Criteria) this;
		}

		public Criteria andMainProductsGreaterThanOrEqualTo(String value) {
			addCriterion("main_products >=", value, "mainProducts");
			return (Criteria) this;
		}

		public Criteria andMainProductsLessThan(String value) {
			addCriterion("main_products <", value, "mainProducts");
			return (Criteria) this;
		}

		public Criteria andMainProductsLessThanOrEqualTo(String value) {
			addCriterion("main_products <=", value, "mainProducts");
			return (Criteria) this;
		}

		public Criteria andMainProductsLike(String value) {
			addCriterion("main_products like", value, "mainProducts");
			return (Criteria) this;
		}

		public Criteria andMainProductsNotLike(String value) {
			addCriterion("main_products not like", value, "mainProducts");
			return (Criteria) this;
		}

		public Criteria andMainProductsIn(List<String> values) {
			addCriterion("main_products in", values, "mainProducts");
			return (Criteria) this;
		}

		public Criteria andMainProductsNotIn(List<String> values) {
			addCriterion("main_products not in", values, "mainProducts");
			return (Criteria) this;
		}

		public Criteria andMainProductsBetween(String value1, String value2) {
			addCriterion("main_products between", value1, value2,
					"mainProducts");
			return (Criteria) this;
		}

		public Criteria andMainProductsNotBetween(String value1, String value2) {
			addCriterion("main_products not between", value1, value2,
					"mainProducts");
			return (Criteria) this;
		}

		public Criteria andRegDateIsNull() {
			addCriterion("reg_date is null");
			return (Criteria) this;
		}

		public Criteria andRegDateIsNotNull() {
			addCriterion("reg_date is not null");
			return (Criteria) this;
		}

		public Criteria andRegDateEqualTo(Date value) {
			addCriterionForJDBCDate("reg_date =", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("reg_date <>", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateGreaterThan(Date value) {
			addCriterionForJDBCDate("reg_date >", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("reg_date >=", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateLessThan(Date value) {
			addCriterionForJDBCDate("reg_date <", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("reg_date <=", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateIn(List<Date> values) {
			addCriterionForJDBCDate("reg_date in", values, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("reg_date not in", values, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("reg_date between", value1, value2,
					"regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("reg_date not between", value1, value2,
					"regDate");
			return (Criteria) this;
		}

		public Criteria andRegMoneyIsNull() {
			addCriterion("reg_money is null");
			return (Criteria) this;
		}

		public Criteria andRegMoneyIsNotNull() {
			addCriterion("reg_money is not null");
			return (Criteria) this;
		}

		public Criteria andRegMoneyEqualTo(Integer value) {
			addCriterion("reg_money =", value, "regMoney");
			return (Criteria) this;
		}

		public Criteria andRegMoneyNotEqualTo(Integer value) {
			addCriterion("reg_money <>", value, "regMoney");
			return (Criteria) this;
		}

		public Criteria andRegMoneyGreaterThan(Integer value) {
			addCriterion("reg_money >", value, "regMoney");
			return (Criteria) this;
		}

		public Criteria andRegMoneyGreaterThanOrEqualTo(Integer value) {
			addCriterion("reg_money >=", value, "regMoney");
			return (Criteria) this;
		}

		public Criteria andRegMoneyLessThan(Integer value) {
			addCriterion("reg_money <", value, "regMoney");
			return (Criteria) this;
		}

		public Criteria andRegMoneyLessThanOrEqualTo(Integer value) {
			addCriterion("reg_money <=", value, "regMoney");
			return (Criteria) this;
		}

		public Criteria andRegMoneyIn(List<Integer> values) {
			addCriterion("reg_money in", values, "regMoney");
			return (Criteria) this;
		}

		public Criteria andRegMoneyNotIn(List<Integer> values) {
			addCriterion("reg_money not in", values, "regMoney");
			return (Criteria) this;
		}

		public Criteria andRegMoneyBetween(Integer value1, Integer value2) {
			addCriterion("reg_money between", value1, value2, "regMoney");
			return (Criteria) this;
		}

		public Criteria andRegMoneyNotBetween(Integer value1, Integer value2) {
			addCriterion("reg_money not between", value1, value2, "regMoney");
			return (Criteria) this;
		}

		public Criteria andMobilephoneIsNull() {
			addCriterion("mobilephone is null");
			return (Criteria) this;
		}

		public Criteria andMobilephoneIsNotNull() {
			addCriterion("mobilephone is not null");
			return (Criteria) this;
		}

		public Criteria andMobilephoneEqualTo(String value) {
			addCriterion("mobilephone =", value, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneNotEqualTo(String value) {
			addCriterion("mobilephone <>", value, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneGreaterThan(String value) {
			addCriterion("mobilephone >", value, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneGreaterThanOrEqualTo(String value) {
			addCriterion("mobilephone >=", value, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneLessThan(String value) {
			addCriterion("mobilephone <", value, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneLessThanOrEqualTo(String value) {
			addCriterion("mobilephone <=", value, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneLike(String value) {
			addCriterion("mobilephone like", value, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneNotLike(String value) {
			addCriterion("mobilephone not like", value, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneIn(List<String> values) {
			addCriterion("mobilephone in", values, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneNotIn(List<String> values) {
			addCriterion("mobilephone not in", values, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneBetween(String value1, String value2) {
			addCriterion("mobilephone between", value1, value2, "mobilephone");
			return (Criteria) this;
		}

		public Criteria andMobilephoneNotBetween(String value1, String value2) {
			addCriterion("mobilephone not between", value1, value2,
					"mobilephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneIsNull() {
			addCriterion("telephone is null");
			return (Criteria) this;
		}

		public Criteria andTelephoneIsNotNull() {
			addCriterion("telephone is not null");
			return (Criteria) this;
		}

		public Criteria andTelephoneEqualTo(String value) {
			addCriterion("telephone =", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotEqualTo(String value) {
			addCriterion("telephone <>", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneGreaterThan(String value) {
			addCriterion("telephone >", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneGreaterThanOrEqualTo(String value) {
			addCriterion("telephone >=", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneLessThan(String value) {
			addCriterion("telephone <", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneLessThanOrEqualTo(String value) {
			addCriterion("telephone <=", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneLike(String value) {
			addCriterion("telephone like", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotLike(String value) {
			addCriterion("telephone not like", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneIn(List<String> values) {
			addCriterion("telephone in", values, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotIn(List<String> values) {
			addCriterion("telephone not in", values, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneBetween(String value1, String value2) {
			addCriterion("telephone between", value1, value2, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotBetween(String value1, String value2) {
			addCriterion("telephone not between", value1, value2, "telephone");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andFaxIsNull() {
			addCriterion("fax is null");
			return (Criteria) this;
		}

		public Criteria andFaxIsNotNull() {
			addCriterion("fax is not null");
			return (Criteria) this;
		}

		public Criteria andFaxEqualTo(String value) {
			addCriterion("fax =", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotEqualTo(String value) {
			addCriterion("fax <>", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxGreaterThan(String value) {
			addCriterion("fax >", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxGreaterThanOrEqualTo(String value) {
			addCriterion("fax >=", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxLessThan(String value) {
			addCriterion("fax <", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxLessThanOrEqualTo(String value) {
			addCriterion("fax <=", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxLike(String value) {
			addCriterion("fax like", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotLike(String value) {
			addCriterion("fax not like", value, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxIn(List<String> values) {
			addCriterion("fax in", values, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotIn(List<String> values) {
			addCriterion("fax not in", values, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxBetween(String value1, String value2) {
			addCriterion("fax between", value1, value2, "fax");
			return (Criteria) this;
		}

		public Criteria andFaxNotBetween(String value1, String value2) {
			addCriterion("fax not between", value1, value2, "fax");
			return (Criteria) this;
		}

		public Criteria andWebsiteIsNull() {
			addCriterion("website is null");
			return (Criteria) this;
		}

		public Criteria andWebsiteIsNotNull() {
			addCriterion("website is not null");
			return (Criteria) this;
		}

		public Criteria andWebsiteEqualTo(String value) {
			addCriterion("website =", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteNotEqualTo(String value) {
			addCriterion("website <>", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteGreaterThan(String value) {
			addCriterion("website >", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteGreaterThanOrEqualTo(String value) {
			addCriterion("website >=", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteLessThan(String value) {
			addCriterion("website <", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteLessThanOrEqualTo(String value) {
			addCriterion("website <=", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteLike(String value) {
			addCriterion("website like", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteNotLike(String value) {
			addCriterion("website not like", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteIn(List<String> values) {
			addCriterion("website in", values, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteNotIn(List<String> values) {
			addCriterion("website not in", values, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteBetween(String value1, String value2) {
			addCriterion("website between", value1, value2, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteNotBetween(String value1, String value2) {
			addCriterion("website not between", value1, value2, "website");
			return (Criteria) this;
		}

		public Criteria andStoredateIsNull() {
			addCriterion("storedate is null");
			return (Criteria) this;
		}

		public Criteria andStoredateIsNotNull() {
			addCriterion("storedate is not null");
			return (Criteria) this;
		}

		public Criteria andStoredateEqualTo(Date value) {
			addCriterion("storedate =", value, "storedate");
			return (Criteria) this;
		}

		public Criteria andStoredateNotEqualTo(Date value) {
			addCriterion("storedate <>", value, "storedate");
			return (Criteria) this;
		}

		public Criteria andStoredateGreaterThan(Date value) {
			addCriterion("storedate >", value, "storedate");
			return (Criteria) this;
		}

		public Criteria andStoredateGreaterThanOrEqualTo(Date value) {
			addCriterion("storedate >=", value, "storedate");
			return (Criteria) this;
		}

		public Criteria andStoredateLessThan(Date value) {
			addCriterion("storedate <", value, "storedate");
			return (Criteria) this;
		}

		public Criteria andStoredateLessThanOrEqualTo(Date value) {
			addCriterion("storedate <=", value, "storedate");
			return (Criteria) this;
		}

		public Criteria andStoredateIn(List<Date> values) {
			addCriterion("storedate in", values, "storedate");
			return (Criteria) this;
		}

		public Criteria andStoredateNotIn(List<Date> values) {
			addCriterion("storedate not in", values, "storedate");
			return (Criteria) this;
		}

		public Criteria andStoredateBetween(Date value1, Date value2) {
			addCriterion("storedate between", value1, value2, "storedate");
			return (Criteria) this;
		}

		public Criteria andStoredateNotBetween(Date value1, Date value2) {
			addCriterion("storedate not between", value1, value2, "storedate");
			return (Criteria) this;
		}

		public Criteria andEmpCountIsNull() {
			addCriterion("emp_count is null");
			return (Criteria) this;
		}

		public Criteria andEmpCountIsNotNull() {
			addCriterion("emp_count is not null");
			return (Criteria) this;
		}

		public Criteria andEmpCountEqualTo(String value) {
			addCriterion("emp_count =", value, "empCount");
			return (Criteria) this;
		}

		public Criteria andEmpCountNotEqualTo(String value) {
			addCriterion("emp_count <>", value, "empCount");
			return (Criteria) this;
		}

		public Criteria andEmpCountGreaterThan(String value) {
			addCriterion("emp_count >", value, "empCount");
			return (Criteria) this;
		}

		public Criteria andEmpCountGreaterThanOrEqualTo(String value) {
			addCriterion("emp_count >=", value, "empCount");
			return (Criteria) this;
		}

		public Criteria andEmpCountLessThan(String value) {
			addCriterion("emp_count <", value, "empCount");
			return (Criteria) this;
		}

		public Criteria andEmpCountLessThanOrEqualTo(String value) {
			addCriterion("emp_count <=", value, "empCount");
			return (Criteria) this;
		}

		public Criteria andEmpCountLike(String value) {
			addCriterion("emp_count like", value, "empCount");
			return (Criteria) this;
		}

		public Criteria andEmpCountNotLike(String value) {
			addCriterion("emp_count not like", value, "empCount");
			return (Criteria) this;
		}

		public Criteria andEmpCountIn(List<String> values) {
			addCriterion("emp_count in", values, "empCount");
			return (Criteria) this;
		}

		public Criteria andEmpCountNotIn(List<String> values) {
			addCriterion("emp_count not in", values, "empCount");
			return (Criteria) this;
		}

		public Criteria andEmpCountBetween(String value1, String value2) {
			addCriterion("emp_count between", value1, value2, "empCount");
			return (Criteria) this;
		}

		public Criteria andEmpCountNotBetween(String value1, String value2) {
			addCriterion("emp_count not between", value1, value2, "empCount");
			return (Criteria) this;
		}

		public Criteria andTurnoverIsNull() {
			addCriterion("turnover is null");
			return (Criteria) this;
		}

		public Criteria andTurnoverIsNotNull() {
			addCriterion("turnover is not null");
			return (Criteria) this;
		}

		public Criteria andTurnoverEqualTo(String value) {
			addCriterion("turnover =", value, "turnover");
			return (Criteria) this;
		}

		public Criteria andTurnoverNotEqualTo(String value) {
			addCriterion("turnover <>", value, "turnover");
			return (Criteria) this;
		}

		public Criteria andTurnoverGreaterThan(String value) {
			addCriterion("turnover >", value, "turnover");
			return (Criteria) this;
		}

		public Criteria andTurnoverGreaterThanOrEqualTo(String value) {
			addCriterion("turnover >=", value, "turnover");
			return (Criteria) this;
		}

		public Criteria andTurnoverLessThan(String value) {
			addCriterion("turnover <", value, "turnover");
			return (Criteria) this;
		}

		public Criteria andTurnoverLessThanOrEqualTo(String value) {
			addCriterion("turnover <=", value, "turnover");
			return (Criteria) this;
		}

		public Criteria andTurnoverLike(String value) {
			addCriterion("turnover like", value, "turnover");
			return (Criteria) this;
		}

		public Criteria andTurnoverNotLike(String value) {
			addCriterion("turnover not like", value, "turnover");
			return (Criteria) this;
		}

		public Criteria andTurnoverIn(List<String> values) {
			addCriterion("turnover in", values, "turnover");
			return (Criteria) this;
		}

		public Criteria andTurnoverNotIn(List<String> values) {
			addCriterion("turnover not in", values, "turnover");
			return (Criteria) this;
		}

		public Criteria andTurnoverBetween(String value1, String value2) {
			addCriterion("turnover between", value1, value2, "turnover");
			return (Criteria) this;
		}

		public Criteria andTurnoverNotBetween(String value1, String value2) {
			addCriterion("turnover not between", value1, value2, "turnover");
			return (Criteria) this;
		}

		public Criteria andWebsiteOuteridIsNull() {
			addCriterion("website_outerid is null");
			return (Criteria) this;
		}

		public Criteria andWebsiteOuteridIsNotNull() {
			addCriterion("website_outerid is not null");
			return (Criteria) this;
		}

		public Criteria andWebsiteOuteridEqualTo(String value) {
			addCriterion("website_outerid =", value, "websiteOuterid");
			return (Criteria) this;
		}

		public Criteria andWebsiteOuteridNotEqualTo(String value) {
			addCriterion("website_outerid <>", value, "websiteOuterid");
			return (Criteria) this;
		}

		public Criteria andWebsiteOuteridGreaterThan(String value) {
			addCriterion("website_outerid >", value, "websiteOuterid");
			return (Criteria) this;
		}

		public Criteria andWebsiteOuteridGreaterThanOrEqualTo(String value) {
			addCriterion("website_outerid >=", value, "websiteOuterid");
			return (Criteria) this;
		}

		public Criteria andWebsiteOuteridLessThan(String value) {
			addCriterion("website_outerid <", value, "websiteOuterid");
			return (Criteria) this;
		}

		public Criteria andWebsiteOuteridLessThanOrEqualTo(String value) {
			addCriterion("website_outerid <=", value, "websiteOuterid");
			return (Criteria) this;
		}

		public Criteria andWebsiteOuteridLike(String value) {
			addCriterion("website_outerid like", value, "websiteOuterid");
			return (Criteria) this;
		}

		public Criteria andWebsiteOuteridNotLike(String value) {
			addCriterion("website_outerid not like", value, "websiteOuterid");
			return (Criteria) this;
		}

		public Criteria andWebsiteOuteridIn(List<String> values) {
			addCriterion("website_outerid in", values, "websiteOuterid");
			return (Criteria) this;
		}

		public Criteria andWebsiteOuteridNotIn(List<String> values) {
			addCriterion("website_outerid not in", values, "websiteOuterid");
			return (Criteria) this;
		}

		public Criteria andWebsiteOuteridBetween(String value1, String value2) {
			addCriterion("website_outerid between", value1, value2,
					"websiteOuterid");
			return (Criteria) this;
		}

		public Criteria andWebsiteOuteridNotBetween(String value1, String value2) {
			addCriterion("website_outerid not between", value1, value2,
					"websiteOuterid");
			return (Criteria) this;
		}

		public Criteria andParentWebIsNull() {
			addCriterion("parent_web is null");
			return (Criteria) this;
		}

		public Criteria andParentWebIsNotNull() {
			addCriterion("parent_web is not null");
			return (Criteria) this;
		}

		public Criteria andParentWebEqualTo(String value) {
			addCriterion("parent_web =", value, "parentWeb");
			return (Criteria) this;
		}

		public Criteria andParentWebNotEqualTo(String value) {
			addCriterion("parent_web <>", value, "parentWeb");
			return (Criteria) this;
		}

		public Criteria andParentWebGreaterThan(String value) {
			addCriterion("parent_web >", value, "parentWeb");
			return (Criteria) this;
		}

		public Criteria andParentWebGreaterThanOrEqualTo(String value) {
			addCriterion("parent_web >=", value, "parentWeb");
			return (Criteria) this;
		}

		public Criteria andParentWebLessThan(String value) {
			addCriterion("parent_web <", value, "parentWeb");
			return (Criteria) this;
		}

		public Criteria andParentWebLessThanOrEqualTo(String value) {
			addCriterion("parent_web <=", value, "parentWeb");
			return (Criteria) this;
		}

		public Criteria andParentWebLike(String value) {
			addCriterion("parent_web like", value, "parentWeb");
			return (Criteria) this;
		}

		public Criteria andParentWebNotLike(String value) {
			addCriterion("parent_web not like", value, "parentWeb");
			return (Criteria) this;
		}

		public Criteria andParentWebIn(List<String> values) {
			addCriterion("parent_web in", values, "parentWeb");
			return (Criteria) this;
		}

		public Criteria andParentWebNotIn(List<String> values) {
			addCriterion("parent_web not in", values, "parentWeb");
			return (Criteria) this;
		}

		public Criteria andParentWebBetween(String value1, String value2) {
			addCriterion("parent_web between", value1, value2, "parentWeb");
			return (Criteria) this;
		}

		public Criteria andParentWebNotBetween(String value1, String value2) {
			addCriterion("parent_web not between", value1, value2, "parentWeb");
			return (Criteria) this;
		}

		public Criteria andFileindexedIsNull() {
			addCriterion("fileindexed is null");
			return (Criteria) this;
		}

		public Criteria andFileindexedIsNotNull() {
			addCriterion("fileindexed is not null");
			return (Criteria) this;
		}

		public Criteria andFileindexedEqualTo(Byte value) {
			addCriterion("fileindexed =", value, "fileindexed");
			return (Criteria) this;
		}

		public Criteria andFileindexedNotEqualTo(Byte value) {
			addCriterion("fileindexed <>", value, "fileindexed");
			return (Criteria) this;
		}

		public Criteria andFileindexedGreaterThan(Byte value) {
			addCriterion("fileindexed >", value, "fileindexed");
			return (Criteria) this;
		}

		public Criteria andFileindexedGreaterThanOrEqualTo(Byte value) {
			addCriterion("fileindexed >=", value, "fileindexed");
			return (Criteria) this;
		}

		public Criteria andFileindexedLessThan(Byte value) {
			addCriterion("fileindexed <", value, "fileindexed");
			return (Criteria) this;
		}

		public Criteria andFileindexedLessThanOrEqualTo(Byte value) {
			addCriterion("fileindexed <=", value, "fileindexed");
			return (Criteria) this;
		}

		public Criteria andFileindexedIn(List<Byte> values) {
			addCriterion("fileindexed in", values, "fileindexed");
			return (Criteria) this;
		}

		public Criteria andFileindexedNotIn(List<Byte> values) {
			addCriterion("fileindexed not in", values, "fileindexed");
			return (Criteria) this;
		}

		public Criteria andFileindexedBetween(Byte value1, Byte value2) {
			addCriterion("fileindexed between", value1, value2, "fileindexed");
			return (Criteria) this;
		}

		public Criteria andFileindexedNotBetween(Byte value1, Byte value2) {
			addCriterion("fileindexed not between", value1, value2,
					"fileindexed");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table uv_company
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uv_company
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 19 10:09:25 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}
