package com.uvcrawler.vo;

import java.util.Date;

public class Company {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.id
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.name
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.industry
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String industry;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.provice
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String provice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.city
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.town
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String town;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.linkman
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String linkman;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.legal_persion
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String legalPersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.main_products
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String mainProducts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.reg_date
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private Date regDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.reg_money
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private Integer regMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.mobilephone
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String mobilephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.telephone
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.address
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.fax
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String fax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.website
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String website;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.storedate
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private Date storedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.emp_count
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String empCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.turnover
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String turnover;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.website_outerid
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String websiteOuterid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.parent_web
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String parentWeb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.fileindexed
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private Byte fileindexed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_company.pro
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String pro;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.id
	 * @return  the value of uv_company.id
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.id
	 * @param id  the value for uv_company.id
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.name
	 * @return  the value of uv_company.name
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.name
	 * @param name  the value for uv_company.name
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.industry
	 * @return  the value of uv_company.industry
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getIndustry() {
		return industry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.industry
	 * @param industry  the value for uv_company.industry
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setIndustry(String industry) {
		this.industry = industry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.provice
	 * @return  the value of uv_company.provice
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getProvice() {
		return provice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.provice
	 * @param provice  the value for uv_company.provice
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setProvice(String provice) {
		this.provice = provice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.city
	 * @return  the value of uv_company.city
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.city
	 * @param city  the value for uv_company.city
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.town
	 * @return  the value of uv_company.town
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getTown() {
		return town;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.town
	 * @param town  the value for uv_company.town
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setTown(String town) {
		this.town = town;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.linkman
	 * @return  the value of uv_company.linkman
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getLinkman() {
		return linkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.linkman
	 * @param linkman  the value for uv_company.linkman
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.legal_persion
	 * @return  the value of uv_company.legal_persion
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getLegalPersion() {
		return legalPersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.legal_persion
	 * @param legalPersion  the value for uv_company.legal_persion
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setLegalPersion(String legalPersion) {
		this.legalPersion = legalPersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.main_products
	 * @return  the value of uv_company.main_products
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getMainProducts() {
		return mainProducts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.main_products
	 * @param mainProducts  the value for uv_company.main_products
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setMainProducts(String mainProducts) {
		this.mainProducts = mainProducts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.reg_date
	 * @return  the value of uv_company.reg_date
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public Date getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.reg_date
	 * @param regDate  the value for uv_company.reg_date
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.reg_money
	 * @return  the value of uv_company.reg_money
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public Integer getRegMoney() {
		return regMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.reg_money
	 * @param regMoney  the value for uv_company.reg_money
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setRegMoney(Integer regMoney) {
		this.regMoney = regMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.mobilephone
	 * @return  the value of uv_company.mobilephone
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getMobilephone() {
		return mobilephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.mobilephone
	 * @param mobilephone  the value for uv_company.mobilephone
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setMobilephone(String mobilephone) {
		this.mobilephone = mobilephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.telephone
	 * @return  the value of uv_company.telephone
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.telephone
	 * @param telephone  the value for uv_company.telephone
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.address
	 * @return  the value of uv_company.address
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.address
	 * @param address  the value for uv_company.address
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.fax
	 * @return  the value of uv_company.fax
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.fax
	 * @param fax  the value for uv_company.fax
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.website
	 * @return  the value of uv_company.website
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getWebsite() {
		return website;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.website
	 * @param website  the value for uv_company.website
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setWebsite(String website) {
		this.website = website;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.storedate
	 * @return  the value of uv_company.storedate
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public Date getStoredate() {
		return storedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.storedate
	 * @param storedate  the value for uv_company.storedate
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setStoredate(Date storedate) {
		this.storedate = storedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.emp_count
	 * @return  the value of uv_company.emp_count
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getEmpCount() {
		return empCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.emp_count
	 * @param empCount  the value for uv_company.emp_count
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setEmpCount(String empCount) {
		this.empCount = empCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.turnover
	 * @return  the value of uv_company.turnover
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getTurnover() {
		return turnover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.turnover
	 * @param turnover  the value for uv_company.turnover
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setTurnover(String turnover) {
		this.turnover = turnover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.website_outerid
	 * @return  the value of uv_company.website_outerid
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getWebsiteOuterid() {
		return websiteOuterid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.website_outerid
	 * @param websiteOuterid  the value for uv_company.website_outerid
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setWebsiteOuterid(String websiteOuterid) {
		this.websiteOuterid = websiteOuterid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.parent_web
	 * @return  the value of uv_company.parent_web
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getParentWeb() {
		return parentWeb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.parent_web
	 * @param parentWeb  the value for uv_company.parent_web
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setParentWeb(String parentWeb) {
		this.parentWeb = parentWeb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.fileindexed
	 * @return  the value of uv_company.fileindexed
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public Byte getFileindexed() {
		return fileindexed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.fileindexed
	 * @param fileindexed  the value for uv_company.fileindexed
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setFileindexed(Byte fileindexed) {
		this.fileindexed = fileindexed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_company.pro
	 * @return  the value of uv_company.pro
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getPro() {
		return pro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_company.pro
	 * @param pro  the value for uv_company.pro
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setPro(String pro) {
		this.pro = pro;
	}
}
