package com.uvcrawler.vo;

public class Crawlinfolog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_crawlinfolog.id
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_crawlinfolog.url
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_crawlinfolog.count
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private Integer count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_crawlinfolog.website_id
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private Integer websiteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_crawlinfolog.parent_url_id
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private Integer parentUrlId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_crawlinfolog.id
	 * @return  the value of uv_crawlinfolog.id
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_crawlinfolog.id
	 * @param id  the value for uv_crawlinfolog.id
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_crawlinfolog.url
	 * @return  the value of uv_crawlinfolog.url
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_crawlinfolog.url
	 * @param url  the value for uv_crawlinfolog.url
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_crawlinfolog.count
	 * @return  the value of uv_crawlinfolog.count
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public Integer getCount() {
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_crawlinfolog.count
	 * @param count  the value for uv_crawlinfolog.count
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setCount(Integer count) {
		this.count = count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_crawlinfolog.website_id
	 * @return  the value of uv_crawlinfolog.website_id
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public Integer getWebsiteId() {
		return websiteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_crawlinfolog.website_id
	 * @param websiteId  the value for uv_crawlinfolog.website_id
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setWebsiteId(Integer websiteId) {
		this.websiteId = websiteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_crawlinfolog.parent_url_id
	 * @return  the value of uv_crawlinfolog.parent_url_id
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public Integer getParentUrlId() {
		return parentUrlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_crawlinfolog.parent_url_id
	 * @param parentUrlId  the value for uv_crawlinfolog.parent_url_id
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setParentUrlId(Integer parentUrlId) {
		this.parentUrlId = parentUrlId;
	}
}
