package com.uvcrawler.vo;

import java.util.Date;

public class Errorlog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_errorlog.id
	 * @mbggenerated  Fri Sep 19 16:16:07 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_errorlog.level
	 * @mbggenerated  Fri Sep 19 16:16:07 CST 2014
	 */
	private String level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_errorlog.log_time
	 * @mbggenerated  Fri Sep 19 16:16:07 CST 2014
	 */
	private Date logTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_errorlog.classname
	 * @mbggenerated  Fri Sep 19 16:16:07 CST 2014
	 */
	private String classname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_errorlog.info
	 * @mbggenerated  Fri Sep 19 16:16:07 CST 2014
	 */
	private String info;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_errorlog.id
	 * @return  the value of uv_errorlog.id
	 * @mbggenerated  Fri Sep 19 16:16:07 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_errorlog.id
	 * @param id  the value for uv_errorlog.id
	 * @mbggenerated  Fri Sep 19 16:16:07 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_errorlog.level
	 * @return  the value of uv_errorlog.level
	 * @mbggenerated  Fri Sep 19 16:16:07 CST 2014
	 */
	public String getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_errorlog.level
	 * @param level  the value for uv_errorlog.level
	 * @mbggenerated  Fri Sep 19 16:16:07 CST 2014
	 */
	public void setLevel(String level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_errorlog.log_time
	 * @return  the value of uv_errorlog.log_time
	 * @mbggenerated  Fri Sep 19 16:16:07 CST 2014
	 */
	public Date getLogTime() {
		return logTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_errorlog.log_time
	 * @param logTime  the value for uv_errorlog.log_time
	 * @mbggenerated  Fri Sep 19 16:16:07 CST 2014
	 */
	public void setLogTime(Date logTime) {
		this.logTime = logTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_errorlog.classname
	 * @return  the value of uv_errorlog.classname
	 * @mbggenerated  Fri Sep 19 16:16:07 CST 2014
	 */
	public String getClassname() {
		return classname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_errorlog.classname
	 * @param classname  the value for uv_errorlog.classname
	 * @mbggenerated  Fri Sep 19 16:16:07 CST 2014
	 */
	public void setClassname(String classname) {
		this.classname = classname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_errorlog.info
	 * @return  the value of uv_errorlog.info
	 * @mbggenerated  Fri Sep 19 16:16:07 CST 2014
	 */
	public String getInfo() {
		return info;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_errorlog.info
	 * @param info  the value for uv_errorlog.info
	 * @mbggenerated  Fri Sep 19 16:16:07 CST 2014
	 */
	public void setInfo(String info) {
		this.info = info;
	}
}