package com.uvcrawler.vo;

import java.util.Date;

public class Proxy {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_proxy.id
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_proxy.host
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String host;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_proxy.port
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String port;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_proxy.username
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_proxy.password
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_proxy.response_time
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private Integer responseTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_proxy.newDate
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private Date newdate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_proxy.id
	 * @return  the value of uv_proxy.id
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_proxy.id
	 * @param id  the value for uv_proxy.id
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_proxy.host
	 * @return  the value of uv_proxy.host
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getHost() {
		return host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_proxy.host
	 * @param host  the value for uv_proxy.host
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setHost(String host) {
		this.host = host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_proxy.port
	 * @return  the value of uv_proxy.port
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getPort() {
		return port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_proxy.port
	 * @param port  the value for uv_proxy.port
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setPort(String port) {
		this.port = port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_proxy.username
	 * @return  the value of uv_proxy.username
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_proxy.username
	 * @param username  the value for uv_proxy.username
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_proxy.password
	 * @return  the value of uv_proxy.password
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_proxy.password
	 * @param password  the value for uv_proxy.password
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_proxy.response_time
	 * @return  the value of uv_proxy.response_time
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public Integer getResponseTime() {
		return responseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_proxy.response_time
	 * @param responseTime  the value for uv_proxy.response_time
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setResponseTime(Integer responseTime) {
		this.responseTime = responseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_proxy.newDate
	 * @return  the value of uv_proxy.newDate
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public Date getNewdate() {
		return newdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_proxy.newDate
	 * @param newdate  the value for uv_proxy.newDate
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setNewdate(Date newdate) {
		this.newdate = newdate;
	}
}
