package com.uvcrawler.vo;

public class Reg_company {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_id
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private Integer regId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_name
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String regName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_industry
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String regIndustry;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_provice
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String regProvice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_city
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String regCity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_town
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String regTown;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_linkman
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String regLinkman;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_legal_persion
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String regLegalPersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_main_products
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String regMainProducts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_regdate
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String regRegdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_regmoney
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String regRegmoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_mobilephone
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String regMobilephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_telephone
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String regTelephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_address
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String regAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_fax
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String regFax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_pro
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String regPro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_emp_count
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String regEmpCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_turnover
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String regTurnover;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_parent_web
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String regParentWeb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.reg_type
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String regType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.website_id
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private Integer websiteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_reg_company.domain
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String domain;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_id
	 * @return  the value of uv_reg_company.reg_id
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public Integer getRegId() {
		return regId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_id
	 * @param regId  the value for uv_reg_company.reg_id
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegId(Integer regId) {
		this.regId = regId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_name
	 * @return  the value of uv_reg_company.reg_name
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getRegName() {
		return regName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_name
	 * @param regName  the value for uv_reg_company.reg_name
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegName(String regName) {
		this.regName = regName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_industry
	 * @return  the value of uv_reg_company.reg_industry
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getRegIndustry() {
		return regIndustry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_industry
	 * @param regIndustry  the value for uv_reg_company.reg_industry
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegIndustry(String regIndustry) {
		this.regIndustry = regIndustry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_provice
	 * @return  the value of uv_reg_company.reg_provice
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getRegProvice() {
		return regProvice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_provice
	 * @param regProvice  the value for uv_reg_company.reg_provice
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegProvice(String regProvice) {
		this.regProvice = regProvice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_city
	 * @return  the value of uv_reg_company.reg_city
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getRegCity() {
		return regCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_city
	 * @param regCity  the value for uv_reg_company.reg_city
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegCity(String regCity) {
		this.regCity = regCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_town
	 * @return  the value of uv_reg_company.reg_town
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getRegTown() {
		return regTown;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_town
	 * @param regTown  the value for uv_reg_company.reg_town
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegTown(String regTown) {
		this.regTown = regTown;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_linkman
	 * @return  the value of uv_reg_company.reg_linkman
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getRegLinkman() {
		return regLinkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_linkman
	 * @param regLinkman  the value for uv_reg_company.reg_linkman
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegLinkman(String regLinkman) {
		this.regLinkman = regLinkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_legal_persion
	 * @return  the value of uv_reg_company.reg_legal_persion
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getRegLegalPersion() {
		return regLegalPersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_legal_persion
	 * @param regLegalPersion  the value for uv_reg_company.reg_legal_persion
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegLegalPersion(String regLegalPersion) {
		this.regLegalPersion = regLegalPersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_main_products
	 * @return  the value of uv_reg_company.reg_main_products
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getRegMainProducts() {
		return regMainProducts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_main_products
	 * @param regMainProducts  the value for uv_reg_company.reg_main_products
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegMainProducts(String regMainProducts) {
		this.regMainProducts = regMainProducts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_regdate
	 * @return  the value of uv_reg_company.reg_regdate
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getRegRegdate() {
		return regRegdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_regdate
	 * @param regRegdate  the value for uv_reg_company.reg_regdate
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegRegdate(String regRegdate) {
		this.regRegdate = regRegdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_regmoney
	 * @return  the value of uv_reg_company.reg_regmoney
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getRegRegmoney() {
		return regRegmoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_regmoney
	 * @param regRegmoney  the value for uv_reg_company.reg_regmoney
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegRegmoney(String regRegmoney) {
		this.regRegmoney = regRegmoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_mobilephone
	 * @return  the value of uv_reg_company.reg_mobilephone
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getRegMobilephone() {
		return regMobilephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_mobilephone
	 * @param regMobilephone  the value for uv_reg_company.reg_mobilephone
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegMobilephone(String regMobilephone) {
		this.regMobilephone = regMobilephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_telephone
	 * @return  the value of uv_reg_company.reg_telephone
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getRegTelephone() {
		return regTelephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_telephone
	 * @param regTelephone  the value for uv_reg_company.reg_telephone
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegTelephone(String regTelephone) {
		this.regTelephone = regTelephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_address
	 * @return  the value of uv_reg_company.reg_address
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getRegAddress() {
		return regAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_address
	 * @param regAddress  the value for uv_reg_company.reg_address
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegAddress(String regAddress) {
		this.regAddress = regAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_fax
	 * @return  the value of uv_reg_company.reg_fax
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getRegFax() {
		return regFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_fax
	 * @param regFax  the value for uv_reg_company.reg_fax
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegFax(String regFax) {
		this.regFax = regFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_pro
	 * @return  the value of uv_reg_company.reg_pro
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getRegPro() {
		return regPro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_pro
	 * @param regPro  the value for uv_reg_company.reg_pro
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegPro(String regPro) {
		this.regPro = regPro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_emp_count
	 * @return  the value of uv_reg_company.reg_emp_count
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getRegEmpCount() {
		return regEmpCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_emp_count
	 * @param regEmpCount  the value for uv_reg_company.reg_emp_count
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegEmpCount(String regEmpCount) {
		this.regEmpCount = regEmpCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_turnover
	 * @return  the value of uv_reg_company.reg_turnover
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getRegTurnover() {
		return regTurnover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_turnover
	 * @param regTurnover  the value for uv_reg_company.reg_turnover
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegTurnover(String regTurnover) {
		this.regTurnover = regTurnover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_parent_web
	 * @return  the value of uv_reg_company.reg_parent_web
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getRegParentWeb() {
		return regParentWeb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_parent_web
	 * @param regParentWeb  the value for uv_reg_company.reg_parent_web
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegParentWeb(String regParentWeb) {
		this.regParentWeb = regParentWeb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.reg_type
	 * @return  the value of uv_reg_company.reg_type
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getRegType() {
		return regType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.reg_type
	 * @param regType  the value for uv_reg_company.reg_type
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRegType(String regType) {
		this.regType = regType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.website_id
	 * @return  the value of uv_reg_company.website_id
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public Integer getWebsiteId() {
		return websiteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.website_id
	 * @param websiteId  the value for uv_reg_company.website_id
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setWebsiteId(Integer websiteId) {
		this.websiteId = websiteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_reg_company.domain
	 * @return  the value of uv_reg_company.domain
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getDomain() {
		return domain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_reg_company.domain
	 * @param domain  the value for uv_reg_company.domain
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setDomain(String domain) {
		this.domain = domain;
	}
}
