package com.uvcrawler.vo;

import java.util.ArrayList;
import java.util.List;

public class Reg_companyExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uv_reg_company
	 * @mbggenerated  Thu Sep 25 22:18:07 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uv_reg_company
	 * @mbggenerated  Thu Sep 25 22:18:07 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uv_reg_company
	 * @mbggenerated  Thu Sep 25 22:18:07 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_reg_company
	 * @mbggenerated  Thu Sep 25 22:18:07 CST 2014
	 */
	public Reg_companyExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_reg_company
	 * @mbggenerated  Thu Sep 25 22:18:07 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_reg_company
	 * @mbggenerated  Thu Sep 25 22:18:07 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_reg_company
	 * @mbggenerated  Thu Sep 25 22:18:07 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_reg_company
	 * @mbggenerated  Thu Sep 25 22:18:07 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_reg_company
	 * @mbggenerated  Thu Sep 25 22:18:07 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_reg_company
	 * @mbggenerated  Thu Sep 25 22:18:07 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_reg_company
	 * @mbggenerated  Thu Sep 25 22:18:07 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_reg_company
	 * @mbggenerated  Thu Sep 25 22:18:07 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_reg_company
	 * @mbggenerated  Thu Sep 25 22:18:07 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_reg_company
	 * @mbggenerated  Thu Sep 25 22:18:07 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table uv_reg_company
	 * @mbggenerated  Thu Sep 25 22:18:07 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRegIdIsNull() {
			addCriterion("reg_id is null");
			return (Criteria) this;
		}

		public Criteria andRegIdIsNotNull() {
			addCriterion("reg_id is not null");
			return (Criteria) this;
		}

		public Criteria andRegIdEqualTo(Integer value) {
			addCriterion("reg_id =", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdNotEqualTo(Integer value) {
			addCriterion("reg_id <>", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdGreaterThan(Integer value) {
			addCriterion("reg_id >", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("reg_id >=", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdLessThan(Integer value) {
			addCriterion("reg_id <", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdLessThanOrEqualTo(Integer value) {
			addCriterion("reg_id <=", value, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdIn(List<Integer> values) {
			addCriterion("reg_id in", values, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdNotIn(List<Integer> values) {
			addCriterion("reg_id not in", values, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdBetween(Integer value1, Integer value2) {
			addCriterion("reg_id between", value1, value2, "regId");
			return (Criteria) this;
		}

		public Criteria andRegIdNotBetween(Integer value1, Integer value2) {
			addCriterion("reg_id not between", value1, value2, "regId");
			return (Criteria) this;
		}

		public Criteria andRegNameIsNull() {
			addCriterion("reg_name is null");
			return (Criteria) this;
		}

		public Criteria andRegNameIsNotNull() {
			addCriterion("reg_name is not null");
			return (Criteria) this;
		}

		public Criteria andRegNameEqualTo(String value) {
			addCriterion("reg_name =", value, "regName");
			return (Criteria) this;
		}

		public Criteria andRegNameNotEqualTo(String value) {
			addCriterion("reg_name <>", value, "regName");
			return (Criteria) this;
		}

		public Criteria andRegNameGreaterThan(String value) {
			addCriterion("reg_name >", value, "regName");
			return (Criteria) this;
		}

		public Criteria andRegNameGreaterThanOrEqualTo(String value) {
			addCriterion("reg_name >=", value, "regName");
			return (Criteria) this;
		}

		public Criteria andRegNameLessThan(String value) {
			addCriterion("reg_name <", value, "regName");
			return (Criteria) this;
		}

		public Criteria andRegNameLessThanOrEqualTo(String value) {
			addCriterion("reg_name <=", value, "regName");
			return (Criteria) this;
		}

		public Criteria andRegNameLike(String value) {
			addCriterion("reg_name like", value, "regName");
			return (Criteria) this;
		}

		public Criteria andRegNameNotLike(String value) {
			addCriterion("reg_name not like", value, "regName");
			return (Criteria) this;
		}

		public Criteria andRegNameIn(List<String> values) {
			addCriterion("reg_name in", values, "regName");
			return (Criteria) this;
		}

		public Criteria andRegNameNotIn(List<String> values) {
			addCriterion("reg_name not in", values, "regName");
			return (Criteria) this;
		}

		public Criteria andRegNameBetween(String value1, String value2) {
			addCriterion("reg_name between", value1, value2, "regName");
			return (Criteria) this;
		}

		public Criteria andRegNameNotBetween(String value1, String value2) {
			addCriterion("reg_name not between", value1, value2, "regName");
			return (Criteria) this;
		}

		public Criteria andRegIndustryIsNull() {
			addCriterion("reg_industry is null");
			return (Criteria) this;
		}

		public Criteria andRegIndustryIsNotNull() {
			addCriterion("reg_industry is not null");
			return (Criteria) this;
		}

		public Criteria andRegIndustryEqualTo(String value) {
			addCriterion("reg_industry =", value, "regIndustry");
			return (Criteria) this;
		}

		public Criteria andRegIndustryNotEqualTo(String value) {
			addCriterion("reg_industry <>", value, "regIndustry");
			return (Criteria) this;
		}

		public Criteria andRegIndustryGreaterThan(String value) {
			addCriterion("reg_industry >", value, "regIndustry");
			return (Criteria) this;
		}

		public Criteria andRegIndustryGreaterThanOrEqualTo(String value) {
			addCriterion("reg_industry >=", value, "regIndustry");
			return (Criteria) this;
		}

		public Criteria andRegIndustryLessThan(String value) {
			addCriterion("reg_industry <", value, "regIndustry");
			return (Criteria) this;
		}

		public Criteria andRegIndustryLessThanOrEqualTo(String value) {
			addCriterion("reg_industry <=", value, "regIndustry");
			return (Criteria) this;
		}

		public Criteria andRegIndustryLike(String value) {
			addCriterion("reg_industry like", value, "regIndustry");
			return (Criteria) this;
		}

		public Criteria andRegIndustryNotLike(String value) {
			addCriterion("reg_industry not like", value, "regIndustry");
			return (Criteria) this;
		}

		public Criteria andRegIndustryIn(List<String> values) {
			addCriterion("reg_industry in", values, "regIndustry");
			return (Criteria) this;
		}

		public Criteria andRegIndustryNotIn(List<String> values) {
			addCriterion("reg_industry not in", values, "regIndustry");
			return (Criteria) this;
		}

		public Criteria andRegIndustryBetween(String value1, String value2) {
			addCriterion("reg_industry between", value1, value2, "regIndustry");
			return (Criteria) this;
		}

		public Criteria andRegIndustryNotBetween(String value1, String value2) {
			addCriterion("reg_industry not between", value1, value2,
					"regIndustry");
			return (Criteria) this;
		}

		public Criteria andRegProviceIsNull() {
			addCriterion("reg_provice is null");
			return (Criteria) this;
		}

		public Criteria andRegProviceIsNotNull() {
			addCriterion("reg_provice is not null");
			return (Criteria) this;
		}

		public Criteria andRegProviceEqualTo(String value) {
			addCriterion("reg_provice =", value, "regProvice");
			return (Criteria) this;
		}

		public Criteria andRegProviceNotEqualTo(String value) {
			addCriterion("reg_provice <>", value, "regProvice");
			return (Criteria) this;
		}

		public Criteria andRegProviceGreaterThan(String value) {
			addCriterion("reg_provice >", value, "regProvice");
			return (Criteria) this;
		}

		public Criteria andRegProviceGreaterThanOrEqualTo(String value) {
			addCriterion("reg_provice >=", value, "regProvice");
			return (Criteria) this;
		}

		public Criteria andRegProviceLessThan(String value) {
			addCriterion("reg_provice <", value, "regProvice");
			return (Criteria) this;
		}

		public Criteria andRegProviceLessThanOrEqualTo(String value) {
			addCriterion("reg_provice <=", value, "regProvice");
			return (Criteria) this;
		}

		public Criteria andRegProviceLike(String value) {
			addCriterion("reg_provice like", value, "regProvice");
			return (Criteria) this;
		}

		public Criteria andRegProviceNotLike(String value) {
			addCriterion("reg_provice not like", value, "regProvice");
			return (Criteria) this;
		}

		public Criteria andRegProviceIn(List<String> values) {
			addCriterion("reg_provice in", values, "regProvice");
			return (Criteria) this;
		}

		public Criteria andRegProviceNotIn(List<String> values) {
			addCriterion("reg_provice not in", values, "regProvice");
			return (Criteria) this;
		}

		public Criteria andRegProviceBetween(String value1, String value2) {
			addCriterion("reg_provice between", value1, value2, "regProvice");
			return (Criteria) this;
		}

		public Criteria andRegProviceNotBetween(String value1, String value2) {
			addCriterion("reg_provice not between", value1, value2,
					"regProvice");
			return (Criteria) this;
		}

		public Criteria andRegCityIsNull() {
			addCriterion("reg_city is null");
			return (Criteria) this;
		}

		public Criteria andRegCityIsNotNull() {
			addCriterion("reg_city is not null");
			return (Criteria) this;
		}

		public Criteria andRegCityEqualTo(String value) {
			addCriterion("reg_city =", value, "regCity");
			return (Criteria) this;
		}

		public Criteria andRegCityNotEqualTo(String value) {
			addCriterion("reg_city <>", value, "regCity");
			return (Criteria) this;
		}

		public Criteria andRegCityGreaterThan(String value) {
			addCriterion("reg_city >", value, "regCity");
			return (Criteria) this;
		}

		public Criteria andRegCityGreaterThanOrEqualTo(String value) {
			addCriterion("reg_city >=", value, "regCity");
			return (Criteria) this;
		}

		public Criteria andRegCityLessThan(String value) {
			addCriterion("reg_city <", value, "regCity");
			return (Criteria) this;
		}

		public Criteria andRegCityLessThanOrEqualTo(String value) {
			addCriterion("reg_city <=", value, "regCity");
			return (Criteria) this;
		}

		public Criteria andRegCityLike(String value) {
			addCriterion("reg_city like", value, "regCity");
			return (Criteria) this;
		}

		public Criteria andRegCityNotLike(String value) {
			addCriterion("reg_city not like", value, "regCity");
			return (Criteria) this;
		}

		public Criteria andRegCityIn(List<String> values) {
			addCriterion("reg_city in", values, "regCity");
			return (Criteria) this;
		}

		public Criteria andRegCityNotIn(List<String> values) {
			addCriterion("reg_city not in", values, "regCity");
			return (Criteria) this;
		}

		public Criteria andRegCityBetween(String value1, String value2) {
			addCriterion("reg_city between", value1, value2, "regCity");
			return (Criteria) this;
		}

		public Criteria andRegCityNotBetween(String value1, String value2) {
			addCriterion("reg_city not between", value1, value2, "regCity");
			return (Criteria) this;
		}

		public Criteria andRegTownIsNull() {
			addCriterion("reg_town is null");
			return (Criteria) this;
		}

		public Criteria andRegTownIsNotNull() {
			addCriterion("reg_town is not null");
			return (Criteria) this;
		}

		public Criteria andRegTownEqualTo(String value) {
			addCriterion("reg_town =", value, "regTown");
			return (Criteria) this;
		}

		public Criteria andRegTownNotEqualTo(String value) {
			addCriterion("reg_town <>", value, "regTown");
			return (Criteria) this;
		}

		public Criteria andRegTownGreaterThan(String value) {
			addCriterion("reg_town >", value, "regTown");
			return (Criteria) this;
		}

		public Criteria andRegTownGreaterThanOrEqualTo(String value) {
			addCriterion("reg_town >=", value, "regTown");
			return (Criteria) this;
		}

		public Criteria andRegTownLessThan(String value) {
			addCriterion("reg_town <", value, "regTown");
			return (Criteria) this;
		}

		public Criteria andRegTownLessThanOrEqualTo(String value) {
			addCriterion("reg_town <=", value, "regTown");
			return (Criteria) this;
		}

		public Criteria andRegTownLike(String value) {
			addCriterion("reg_town like", value, "regTown");
			return (Criteria) this;
		}

		public Criteria andRegTownNotLike(String value) {
			addCriterion("reg_town not like", value, "regTown");
			return (Criteria) this;
		}

		public Criteria andRegTownIn(List<String> values) {
			addCriterion("reg_town in", values, "regTown");
			return (Criteria) this;
		}

		public Criteria andRegTownNotIn(List<String> values) {
			addCriterion("reg_town not in", values, "regTown");
			return (Criteria) this;
		}

		public Criteria andRegTownBetween(String value1, String value2) {
			addCriterion("reg_town between", value1, value2, "regTown");
			return (Criteria) this;
		}

		public Criteria andRegTownNotBetween(String value1, String value2) {
			addCriterion("reg_town not between", value1, value2, "regTown");
			return (Criteria) this;
		}

		public Criteria andRegLinkmanIsNull() {
			addCriterion("reg_linkman is null");
			return (Criteria) this;
		}

		public Criteria andRegLinkmanIsNotNull() {
			addCriterion("reg_linkman is not null");
			return (Criteria) this;
		}

		public Criteria andRegLinkmanEqualTo(String value) {
			addCriterion("reg_linkman =", value, "regLinkman");
			return (Criteria) this;
		}

		public Criteria andRegLinkmanNotEqualTo(String value) {
			addCriterion("reg_linkman <>", value, "regLinkman");
			return (Criteria) this;
		}

		public Criteria andRegLinkmanGreaterThan(String value) {
			addCriterion("reg_linkman >", value, "regLinkman");
			return (Criteria) this;
		}

		public Criteria andRegLinkmanGreaterThanOrEqualTo(String value) {
			addCriterion("reg_linkman >=", value, "regLinkman");
			return (Criteria) this;
		}

		public Criteria andRegLinkmanLessThan(String value) {
			addCriterion("reg_linkman <", value, "regLinkman");
			return (Criteria) this;
		}

		public Criteria andRegLinkmanLessThanOrEqualTo(String value) {
			addCriterion("reg_linkman <=", value, "regLinkman");
			return (Criteria) this;
		}

		public Criteria andRegLinkmanLike(String value) {
			addCriterion("reg_linkman like", value, "regLinkman");
			return (Criteria) this;
		}

		public Criteria andRegLinkmanNotLike(String value) {
			addCriterion("reg_linkman not like", value, "regLinkman");
			return (Criteria) this;
		}

		public Criteria andRegLinkmanIn(List<String> values) {
			addCriterion("reg_linkman in", values, "regLinkman");
			return (Criteria) this;
		}

		public Criteria andRegLinkmanNotIn(List<String> values) {
			addCriterion("reg_linkman not in", values, "regLinkman");
			return (Criteria) this;
		}

		public Criteria andRegLinkmanBetween(String value1, String value2) {
			addCriterion("reg_linkman between", value1, value2, "regLinkman");
			return (Criteria) this;
		}

		public Criteria andRegLinkmanNotBetween(String value1, String value2) {
			addCriterion("reg_linkman not between", value1, value2,
					"regLinkman");
			return (Criteria) this;
		}

		public Criteria andRegLegalPersionIsNull() {
			addCriterion("reg_legal_persion is null");
			return (Criteria) this;
		}

		public Criteria andRegLegalPersionIsNotNull() {
			addCriterion("reg_legal_persion is not null");
			return (Criteria) this;
		}

		public Criteria andRegLegalPersionEqualTo(String value) {
			addCriterion("reg_legal_persion =", value, "regLegalPersion");
			return (Criteria) this;
		}

		public Criteria andRegLegalPersionNotEqualTo(String value) {
			addCriterion("reg_legal_persion <>", value, "regLegalPersion");
			return (Criteria) this;
		}

		public Criteria andRegLegalPersionGreaterThan(String value) {
			addCriterion("reg_legal_persion >", value, "regLegalPersion");
			return (Criteria) this;
		}

		public Criteria andRegLegalPersionGreaterThanOrEqualTo(String value) {
			addCriterion("reg_legal_persion >=", value, "regLegalPersion");
			return (Criteria) this;
		}

		public Criteria andRegLegalPersionLessThan(String value) {
			addCriterion("reg_legal_persion <", value, "regLegalPersion");
			return (Criteria) this;
		}

		public Criteria andRegLegalPersionLessThanOrEqualTo(String value) {
			addCriterion("reg_legal_persion <=", value, "regLegalPersion");
			return (Criteria) this;
		}

		public Criteria andRegLegalPersionLike(String value) {
			addCriterion("reg_legal_persion like", value, "regLegalPersion");
			return (Criteria) this;
		}

		public Criteria andRegLegalPersionNotLike(String value) {
			addCriterion("reg_legal_persion not like", value, "regLegalPersion");
			return (Criteria) this;
		}

		public Criteria andRegLegalPersionIn(List<String> values) {
			addCriterion("reg_legal_persion in", values, "regLegalPersion");
			return (Criteria) this;
		}

		public Criteria andRegLegalPersionNotIn(List<String> values) {
			addCriterion("reg_legal_persion not in", values, "regLegalPersion");
			return (Criteria) this;
		}

		public Criteria andRegLegalPersionBetween(String value1, String value2) {
			addCriterion("reg_legal_persion between", value1, value2,
					"regLegalPersion");
			return (Criteria) this;
		}

		public Criteria andRegLegalPersionNotBetween(String value1,
				String value2) {
			addCriterion("reg_legal_persion not between", value1, value2,
					"regLegalPersion");
			return (Criteria) this;
		}

		public Criteria andRegMainProductsIsNull() {
			addCriterion("reg_main_products is null");
			return (Criteria) this;
		}

		public Criteria andRegMainProductsIsNotNull() {
			addCriterion("reg_main_products is not null");
			return (Criteria) this;
		}

		public Criteria andRegMainProductsEqualTo(String value) {
			addCriterion("reg_main_products =", value, "regMainProducts");
			return (Criteria) this;
		}

		public Criteria andRegMainProductsNotEqualTo(String value) {
			addCriterion("reg_main_products <>", value, "regMainProducts");
			return (Criteria) this;
		}

		public Criteria andRegMainProductsGreaterThan(String value) {
			addCriterion("reg_main_products >", value, "regMainProducts");
			return (Criteria) this;
		}

		public Criteria andRegMainProductsGreaterThanOrEqualTo(String value) {
			addCriterion("reg_main_products >=", value, "regMainProducts");
			return (Criteria) this;
		}

		public Criteria andRegMainProductsLessThan(String value) {
			addCriterion("reg_main_products <", value, "regMainProducts");
			return (Criteria) this;
		}

		public Criteria andRegMainProductsLessThanOrEqualTo(String value) {
			addCriterion("reg_main_products <=", value, "regMainProducts");
			return (Criteria) this;
		}

		public Criteria andRegMainProductsLike(String value) {
			addCriterion("reg_main_products like", value, "regMainProducts");
			return (Criteria) this;
		}

		public Criteria andRegMainProductsNotLike(String value) {
			addCriterion("reg_main_products not like", value, "regMainProducts");
			return (Criteria) this;
		}

		public Criteria andRegMainProductsIn(List<String> values) {
			addCriterion("reg_main_products in", values, "regMainProducts");
			return (Criteria) this;
		}

		public Criteria andRegMainProductsNotIn(List<String> values) {
			addCriterion("reg_main_products not in", values, "regMainProducts");
			return (Criteria) this;
		}

		public Criteria andRegMainProductsBetween(String value1, String value2) {
			addCriterion("reg_main_products between", value1, value2,
					"regMainProducts");
			return (Criteria) this;
		}

		public Criteria andRegMainProductsNotBetween(String value1,
				String value2) {
			addCriterion("reg_main_products not between", value1, value2,
					"regMainProducts");
			return (Criteria) this;
		}

		public Criteria andRegRegdateIsNull() {
			addCriterion("reg_regdate is null");
			return (Criteria) this;
		}

		public Criteria andRegRegdateIsNotNull() {
			addCriterion("reg_regdate is not null");
			return (Criteria) this;
		}

		public Criteria andRegRegdateEqualTo(String value) {
			addCriterion("reg_regdate =", value, "regRegdate");
			return (Criteria) this;
		}

		public Criteria andRegRegdateNotEqualTo(String value) {
			addCriterion("reg_regdate <>", value, "regRegdate");
			return (Criteria) this;
		}

		public Criteria andRegRegdateGreaterThan(String value) {
			addCriterion("reg_regdate >", value, "regRegdate");
			return (Criteria) this;
		}

		public Criteria andRegRegdateGreaterThanOrEqualTo(String value) {
			addCriterion("reg_regdate >=", value, "regRegdate");
			return (Criteria) this;
		}

		public Criteria andRegRegdateLessThan(String value) {
			addCriterion("reg_regdate <", value, "regRegdate");
			return (Criteria) this;
		}

		public Criteria andRegRegdateLessThanOrEqualTo(String value) {
			addCriterion("reg_regdate <=", value, "regRegdate");
			return (Criteria) this;
		}

		public Criteria andRegRegdateLike(String value) {
			addCriterion("reg_regdate like", value, "regRegdate");
			return (Criteria) this;
		}

		public Criteria andRegRegdateNotLike(String value) {
			addCriterion("reg_regdate not like", value, "regRegdate");
			return (Criteria) this;
		}

		public Criteria andRegRegdateIn(List<String> values) {
			addCriterion("reg_regdate in", values, "regRegdate");
			return (Criteria) this;
		}

		public Criteria andRegRegdateNotIn(List<String> values) {
			addCriterion("reg_regdate not in", values, "regRegdate");
			return (Criteria) this;
		}

		public Criteria andRegRegdateBetween(String value1, String value2) {
			addCriterion("reg_regdate between", value1, value2, "regRegdate");
			return (Criteria) this;
		}

		public Criteria andRegRegdateNotBetween(String value1, String value2) {
			addCriterion("reg_regdate not between", value1, value2,
					"regRegdate");
			return (Criteria) this;
		}

		public Criteria andRegRegmoneyIsNull() {
			addCriterion("reg_regmoney is null");
			return (Criteria) this;
		}

		public Criteria andRegRegmoneyIsNotNull() {
			addCriterion("reg_regmoney is not null");
			return (Criteria) this;
		}

		public Criteria andRegRegmoneyEqualTo(String value) {
			addCriterion("reg_regmoney =", value, "regRegmoney");
			return (Criteria) this;
		}

		public Criteria andRegRegmoneyNotEqualTo(String value) {
			addCriterion("reg_regmoney <>", value, "regRegmoney");
			return (Criteria) this;
		}

		public Criteria andRegRegmoneyGreaterThan(String value) {
			addCriterion("reg_regmoney >", value, "regRegmoney");
			return (Criteria) this;
		}

		public Criteria andRegRegmoneyGreaterThanOrEqualTo(String value) {
			addCriterion("reg_regmoney >=", value, "regRegmoney");
			return (Criteria) this;
		}

		public Criteria andRegRegmoneyLessThan(String value) {
			addCriterion("reg_regmoney <", value, "regRegmoney");
			return (Criteria) this;
		}

		public Criteria andRegRegmoneyLessThanOrEqualTo(String value) {
			addCriterion("reg_regmoney <=", value, "regRegmoney");
			return (Criteria) this;
		}

		public Criteria andRegRegmoneyLike(String value) {
			addCriterion("reg_regmoney like", value, "regRegmoney");
			return (Criteria) this;
		}

		public Criteria andRegRegmoneyNotLike(String value) {
			addCriterion("reg_regmoney not like", value, "regRegmoney");
			return (Criteria) this;
		}

		public Criteria andRegRegmoneyIn(List<String> values) {
			addCriterion("reg_regmoney in", values, "regRegmoney");
			return (Criteria) this;
		}

		public Criteria andRegRegmoneyNotIn(List<String> values) {
			addCriterion("reg_regmoney not in", values, "regRegmoney");
			return (Criteria) this;
		}

		public Criteria andRegRegmoneyBetween(String value1, String value2) {
			addCriterion("reg_regmoney between", value1, value2, "regRegmoney");
			return (Criteria) this;
		}

		public Criteria andRegRegmoneyNotBetween(String value1, String value2) {
			addCriterion("reg_regmoney not between", value1, value2,
					"regRegmoney");
			return (Criteria) this;
		}

		public Criteria andRegMobilephoneIsNull() {
			addCriterion("reg_mobilephone is null");
			return (Criteria) this;
		}

		public Criteria andRegMobilephoneIsNotNull() {
			addCriterion("reg_mobilephone is not null");
			return (Criteria) this;
		}

		public Criteria andRegMobilephoneEqualTo(String value) {
			addCriterion("reg_mobilephone =", value, "regMobilephone");
			return (Criteria) this;
		}

		public Criteria andRegMobilephoneNotEqualTo(String value) {
			addCriterion("reg_mobilephone <>", value, "regMobilephone");
			return (Criteria) this;
		}

		public Criteria andRegMobilephoneGreaterThan(String value) {
			addCriterion("reg_mobilephone >", value, "regMobilephone");
			return (Criteria) this;
		}

		public Criteria andRegMobilephoneGreaterThanOrEqualTo(String value) {
			addCriterion("reg_mobilephone >=", value, "regMobilephone");
			return (Criteria) this;
		}

		public Criteria andRegMobilephoneLessThan(String value) {
			addCriterion("reg_mobilephone <", value, "regMobilephone");
			return (Criteria) this;
		}

		public Criteria andRegMobilephoneLessThanOrEqualTo(String value) {
			addCriterion("reg_mobilephone <=", value, "regMobilephone");
			return (Criteria) this;
		}

		public Criteria andRegMobilephoneLike(String value) {
			addCriterion("reg_mobilephone like", value, "regMobilephone");
			return (Criteria) this;
		}

		public Criteria andRegMobilephoneNotLike(String value) {
			addCriterion("reg_mobilephone not like", value, "regMobilephone");
			return (Criteria) this;
		}

		public Criteria andRegMobilephoneIn(List<String> values) {
			addCriterion("reg_mobilephone in", values, "regMobilephone");
			return (Criteria) this;
		}

		public Criteria andRegMobilephoneNotIn(List<String> values) {
			addCriterion("reg_mobilephone not in", values, "regMobilephone");
			return (Criteria) this;
		}

		public Criteria andRegMobilephoneBetween(String value1, String value2) {
			addCriterion("reg_mobilephone between", value1, value2,
					"regMobilephone");
			return (Criteria) this;
		}

		public Criteria andRegMobilephoneNotBetween(String value1, String value2) {
			addCriterion("reg_mobilephone not between", value1, value2,
					"regMobilephone");
			return (Criteria) this;
		}

		public Criteria andRegTelephoneIsNull() {
			addCriterion("reg_telephone is null");
			return (Criteria) this;
		}

		public Criteria andRegTelephoneIsNotNull() {
			addCriterion("reg_telephone is not null");
			return (Criteria) this;
		}

		public Criteria andRegTelephoneEqualTo(String value) {
			addCriterion("reg_telephone =", value, "regTelephone");
			return (Criteria) this;
		}

		public Criteria andRegTelephoneNotEqualTo(String value) {
			addCriterion("reg_telephone <>", value, "regTelephone");
			return (Criteria) this;
		}

		public Criteria andRegTelephoneGreaterThan(String value) {
			addCriterion("reg_telephone >", value, "regTelephone");
			return (Criteria) this;
		}

		public Criteria andRegTelephoneGreaterThanOrEqualTo(String value) {
			addCriterion("reg_telephone >=", value, "regTelephone");
			return (Criteria) this;
		}

		public Criteria andRegTelephoneLessThan(String value) {
			addCriterion("reg_telephone <", value, "regTelephone");
			return (Criteria) this;
		}

		public Criteria andRegTelephoneLessThanOrEqualTo(String value) {
			addCriterion("reg_telephone <=", value, "regTelephone");
			return (Criteria) this;
		}

		public Criteria andRegTelephoneLike(String value) {
			addCriterion("reg_telephone like", value, "regTelephone");
			return (Criteria) this;
		}

		public Criteria andRegTelephoneNotLike(String value) {
			addCriterion("reg_telephone not like", value, "regTelephone");
			return (Criteria) this;
		}

		public Criteria andRegTelephoneIn(List<String> values) {
			addCriterion("reg_telephone in", values, "regTelephone");
			return (Criteria) this;
		}

		public Criteria andRegTelephoneNotIn(List<String> values) {
			addCriterion("reg_telephone not in", values, "regTelephone");
			return (Criteria) this;
		}

		public Criteria andRegTelephoneBetween(String value1, String value2) {
			addCriterion("reg_telephone between", value1, value2,
					"regTelephone");
			return (Criteria) this;
		}

		public Criteria andRegTelephoneNotBetween(String value1, String value2) {
			addCriterion("reg_telephone not between", value1, value2,
					"regTelephone");
			return (Criteria) this;
		}

		public Criteria andRegAddressIsNull() {
			addCriterion("reg_address is null");
			return (Criteria) this;
		}

		public Criteria andRegAddressIsNotNull() {
			addCriterion("reg_address is not null");
			return (Criteria) this;
		}

		public Criteria andRegAddressEqualTo(String value) {
			addCriterion("reg_address =", value, "regAddress");
			return (Criteria) this;
		}

		public Criteria andRegAddressNotEqualTo(String value) {
			addCriterion("reg_address <>", value, "regAddress");
			return (Criteria) this;
		}

		public Criteria andRegAddressGreaterThan(String value) {
			addCriterion("reg_address >", value, "regAddress");
			return (Criteria) this;
		}

		public Criteria andRegAddressGreaterThanOrEqualTo(String value) {
			addCriterion("reg_address >=", value, "regAddress");
			return (Criteria) this;
		}

		public Criteria andRegAddressLessThan(String value) {
			addCriterion("reg_address <", value, "regAddress");
			return (Criteria) this;
		}

		public Criteria andRegAddressLessThanOrEqualTo(String value) {
			addCriterion("reg_address <=", value, "regAddress");
			return (Criteria) this;
		}

		public Criteria andRegAddressLike(String value) {
			addCriterion("reg_address like", value, "regAddress");
			return (Criteria) this;
		}

		public Criteria andRegAddressNotLike(String value) {
			addCriterion("reg_address not like", value, "regAddress");
			return (Criteria) this;
		}

		public Criteria andRegAddressIn(List<String> values) {
			addCriterion("reg_address in", values, "regAddress");
			return (Criteria) this;
		}

		public Criteria andRegAddressNotIn(List<String> values) {
			addCriterion("reg_address not in", values, "regAddress");
			return (Criteria) this;
		}

		public Criteria andRegAddressBetween(String value1, String value2) {
			addCriterion("reg_address between", value1, value2, "regAddress");
			return (Criteria) this;
		}

		public Criteria andRegAddressNotBetween(String value1, String value2) {
			addCriterion("reg_address not between", value1, value2,
					"regAddress");
			return (Criteria) this;
		}

		public Criteria andRegFaxIsNull() {
			addCriterion("reg_fax is null");
			return (Criteria) this;
		}

		public Criteria andRegFaxIsNotNull() {
			addCriterion("reg_fax is not null");
			return (Criteria) this;
		}

		public Criteria andRegFaxEqualTo(String value) {
			addCriterion("reg_fax =", value, "regFax");
			return (Criteria) this;
		}

		public Criteria andRegFaxNotEqualTo(String value) {
			addCriterion("reg_fax <>", value, "regFax");
			return (Criteria) this;
		}

		public Criteria andRegFaxGreaterThan(String value) {
			addCriterion("reg_fax >", value, "regFax");
			return (Criteria) this;
		}

		public Criteria andRegFaxGreaterThanOrEqualTo(String value) {
			addCriterion("reg_fax >=", value, "regFax");
			return (Criteria) this;
		}

		public Criteria andRegFaxLessThan(String value) {
			addCriterion("reg_fax <", value, "regFax");
			return (Criteria) this;
		}

		public Criteria andRegFaxLessThanOrEqualTo(String value) {
			addCriterion("reg_fax <=", value, "regFax");
			return (Criteria) this;
		}

		public Criteria andRegFaxLike(String value) {
			addCriterion("reg_fax like", value, "regFax");
			return (Criteria) this;
		}

		public Criteria andRegFaxNotLike(String value) {
			addCriterion("reg_fax not like", value, "regFax");
			return (Criteria) this;
		}

		public Criteria andRegFaxIn(List<String> values) {
			addCriterion("reg_fax in", values, "regFax");
			return (Criteria) this;
		}

		public Criteria andRegFaxNotIn(List<String> values) {
			addCriterion("reg_fax not in", values, "regFax");
			return (Criteria) this;
		}

		public Criteria andRegFaxBetween(String value1, String value2) {
			addCriterion("reg_fax between", value1, value2, "regFax");
			return (Criteria) this;
		}

		public Criteria andRegFaxNotBetween(String value1, String value2) {
			addCriterion("reg_fax not between", value1, value2, "regFax");
			return (Criteria) this;
		}

		public Criteria andRegProIsNull() {
			addCriterion("reg_pro is null");
			return (Criteria) this;
		}

		public Criteria andRegProIsNotNull() {
			addCriterion("reg_pro is not null");
			return (Criteria) this;
		}

		public Criteria andRegProEqualTo(String value) {
			addCriterion("reg_pro =", value, "regPro");
			return (Criteria) this;
		}

		public Criteria andRegProNotEqualTo(String value) {
			addCriterion("reg_pro <>", value, "regPro");
			return (Criteria) this;
		}

		public Criteria andRegProGreaterThan(String value) {
			addCriterion("reg_pro >", value, "regPro");
			return (Criteria) this;
		}

		public Criteria andRegProGreaterThanOrEqualTo(String value) {
			addCriterion("reg_pro >=", value, "regPro");
			return (Criteria) this;
		}

		public Criteria andRegProLessThan(String value) {
			addCriterion("reg_pro <", value, "regPro");
			return (Criteria) this;
		}

		public Criteria andRegProLessThanOrEqualTo(String value) {
			addCriterion("reg_pro <=", value, "regPro");
			return (Criteria) this;
		}

		public Criteria andRegProLike(String value) {
			addCriterion("reg_pro like", value, "regPro");
			return (Criteria) this;
		}

		public Criteria andRegProNotLike(String value) {
			addCriterion("reg_pro not like", value, "regPro");
			return (Criteria) this;
		}

		public Criteria andRegProIn(List<String> values) {
			addCriterion("reg_pro in", values, "regPro");
			return (Criteria) this;
		}

		public Criteria andRegProNotIn(List<String> values) {
			addCriterion("reg_pro not in", values, "regPro");
			return (Criteria) this;
		}

		public Criteria andRegProBetween(String value1, String value2) {
			addCriterion("reg_pro between", value1, value2, "regPro");
			return (Criteria) this;
		}

		public Criteria andRegProNotBetween(String value1, String value2) {
			addCriterion("reg_pro not between", value1, value2, "regPro");
			return (Criteria) this;
		}

		public Criteria andRegEmpCountIsNull() {
			addCriterion("reg_emp_count is null");
			return (Criteria) this;
		}

		public Criteria andRegEmpCountIsNotNull() {
			addCriterion("reg_emp_count is not null");
			return (Criteria) this;
		}

		public Criteria andRegEmpCountEqualTo(String value) {
			addCriterion("reg_emp_count =", value, "regEmpCount");
			return (Criteria) this;
		}

		public Criteria andRegEmpCountNotEqualTo(String value) {
			addCriterion("reg_emp_count <>", value, "regEmpCount");
			return (Criteria) this;
		}

		public Criteria andRegEmpCountGreaterThan(String value) {
			addCriterion("reg_emp_count >", value, "regEmpCount");
			return (Criteria) this;
		}

		public Criteria andRegEmpCountGreaterThanOrEqualTo(String value) {
			addCriterion("reg_emp_count >=", value, "regEmpCount");
			return (Criteria) this;
		}

		public Criteria andRegEmpCountLessThan(String value) {
			addCriterion("reg_emp_count <", value, "regEmpCount");
			return (Criteria) this;
		}

		public Criteria andRegEmpCountLessThanOrEqualTo(String value) {
			addCriterion("reg_emp_count <=", value, "regEmpCount");
			return (Criteria) this;
		}

		public Criteria andRegEmpCountLike(String value) {
			addCriterion("reg_emp_count like", value, "regEmpCount");
			return (Criteria) this;
		}

		public Criteria andRegEmpCountNotLike(String value) {
			addCriterion("reg_emp_count not like", value, "regEmpCount");
			return (Criteria) this;
		}

		public Criteria andRegEmpCountIn(List<String> values) {
			addCriterion("reg_emp_count in", values, "regEmpCount");
			return (Criteria) this;
		}

		public Criteria andRegEmpCountNotIn(List<String> values) {
			addCriterion("reg_emp_count not in", values, "regEmpCount");
			return (Criteria) this;
		}

		public Criteria andRegEmpCountBetween(String value1, String value2) {
			addCriterion("reg_emp_count between", value1, value2, "regEmpCount");
			return (Criteria) this;
		}

		public Criteria andRegEmpCountNotBetween(String value1, String value2) {
			addCriterion("reg_emp_count not between", value1, value2,
					"regEmpCount");
			return (Criteria) this;
		}

		public Criteria andRegTurnoverIsNull() {
			addCriterion("reg_turnover is null");
			return (Criteria) this;
		}

		public Criteria andRegTurnoverIsNotNull() {
			addCriterion("reg_turnover is not null");
			return (Criteria) this;
		}

		public Criteria andRegTurnoverEqualTo(String value) {
			addCriterion("reg_turnover =", value, "regTurnover");
			return (Criteria) this;
		}

		public Criteria andRegTurnoverNotEqualTo(String value) {
			addCriterion("reg_turnover <>", value, "regTurnover");
			return (Criteria) this;
		}

		public Criteria andRegTurnoverGreaterThan(String value) {
			addCriterion("reg_turnover >", value, "regTurnover");
			return (Criteria) this;
		}

		public Criteria andRegTurnoverGreaterThanOrEqualTo(String value) {
			addCriterion("reg_turnover >=", value, "regTurnover");
			return (Criteria) this;
		}

		public Criteria andRegTurnoverLessThan(String value) {
			addCriterion("reg_turnover <", value, "regTurnover");
			return (Criteria) this;
		}

		public Criteria andRegTurnoverLessThanOrEqualTo(String value) {
			addCriterion("reg_turnover <=", value, "regTurnover");
			return (Criteria) this;
		}

		public Criteria andRegTurnoverLike(String value) {
			addCriterion("reg_turnover like", value, "regTurnover");
			return (Criteria) this;
		}

		public Criteria andRegTurnoverNotLike(String value) {
			addCriterion("reg_turnover not like", value, "regTurnover");
			return (Criteria) this;
		}

		public Criteria andRegTurnoverIn(List<String> values) {
			addCriterion("reg_turnover in", values, "regTurnover");
			return (Criteria) this;
		}

		public Criteria andRegTurnoverNotIn(List<String> values) {
			addCriterion("reg_turnover not in", values, "regTurnover");
			return (Criteria) this;
		}

		public Criteria andRegTurnoverBetween(String value1, String value2) {
			addCriterion("reg_turnover between", value1, value2, "regTurnover");
			return (Criteria) this;
		}

		public Criteria andRegTurnoverNotBetween(String value1, String value2) {
			addCriterion("reg_turnover not between", value1, value2,
					"regTurnover");
			return (Criteria) this;
		}

		public Criteria andRegParentWebIsNull() {
			addCriterion("reg_parent_web is null");
			return (Criteria) this;
		}

		public Criteria andRegParentWebIsNotNull() {
			addCriterion("reg_parent_web is not null");
			return (Criteria) this;
		}

		public Criteria andRegParentWebEqualTo(String value) {
			addCriterion("reg_parent_web =", value, "regParentWeb");
			return (Criteria) this;
		}

		public Criteria andRegParentWebNotEqualTo(String value) {
			addCriterion("reg_parent_web <>", value, "regParentWeb");
			return (Criteria) this;
		}

		public Criteria andRegParentWebGreaterThan(String value) {
			addCriterion("reg_parent_web >", value, "regParentWeb");
			return (Criteria) this;
		}

		public Criteria andRegParentWebGreaterThanOrEqualTo(String value) {
			addCriterion("reg_parent_web >=", value, "regParentWeb");
			return (Criteria) this;
		}

		public Criteria andRegParentWebLessThan(String value) {
			addCriterion("reg_parent_web <", value, "regParentWeb");
			return (Criteria) this;
		}

		public Criteria andRegParentWebLessThanOrEqualTo(String value) {
			addCriterion("reg_parent_web <=", value, "regParentWeb");
			return (Criteria) this;
		}

		public Criteria andRegParentWebLike(String value) {
			addCriterion("reg_parent_web like", value, "regParentWeb");
			return (Criteria) this;
		}

		public Criteria andRegParentWebNotLike(String value) {
			addCriterion("reg_parent_web not like", value, "regParentWeb");
			return (Criteria) this;
		}

		public Criteria andRegParentWebIn(List<String> values) {
			addCriterion("reg_parent_web in", values, "regParentWeb");
			return (Criteria) this;
		}

		public Criteria andRegParentWebNotIn(List<String> values) {
			addCriterion("reg_parent_web not in", values, "regParentWeb");
			return (Criteria) this;
		}

		public Criteria andRegParentWebBetween(String value1, String value2) {
			addCriterion("reg_parent_web between", value1, value2,
					"regParentWeb");
			return (Criteria) this;
		}

		public Criteria andRegParentWebNotBetween(String value1, String value2) {
			addCriterion("reg_parent_web not between", value1, value2,
					"regParentWeb");
			return (Criteria) this;
		}

		public Criteria andRegTypeIsNull() {
			addCriterion("reg_type is null");
			return (Criteria) this;
		}

		public Criteria andRegTypeIsNotNull() {
			addCriterion("reg_type is not null");
			return (Criteria) this;
		}

		public Criteria andRegTypeEqualTo(String value) {
			addCriterion("reg_type =", value, "regType");
			return (Criteria) this;
		}

		public Criteria andRegTypeNotEqualTo(String value) {
			addCriterion("reg_type <>", value, "regType");
			return (Criteria) this;
		}

		public Criteria andRegTypeGreaterThan(String value) {
			addCriterion("reg_type >", value, "regType");
			return (Criteria) this;
		}

		public Criteria andRegTypeGreaterThanOrEqualTo(String value) {
			addCriterion("reg_type >=", value, "regType");
			return (Criteria) this;
		}

		public Criteria andRegTypeLessThan(String value) {
			addCriterion("reg_type <", value, "regType");
			return (Criteria) this;
		}

		public Criteria andRegTypeLessThanOrEqualTo(String value) {
			addCriterion("reg_type <=", value, "regType");
			return (Criteria) this;
		}

		public Criteria andRegTypeLike(String value) {
			addCriterion("reg_type like", value, "regType");
			return (Criteria) this;
		}

		public Criteria andRegTypeNotLike(String value) {
			addCriterion("reg_type not like", value, "regType");
			return (Criteria) this;
		}

		public Criteria andRegTypeIn(List<String> values) {
			addCriterion("reg_type in", values, "regType");
			return (Criteria) this;
		}

		public Criteria andRegTypeNotIn(List<String> values) {
			addCriterion("reg_type not in", values, "regType");
			return (Criteria) this;
		}

		public Criteria andRegTypeBetween(String value1, String value2) {
			addCriterion("reg_type between", value1, value2, "regType");
			return (Criteria) this;
		}

		public Criteria andRegTypeNotBetween(String value1, String value2) {
			addCriterion("reg_type not between", value1, value2, "regType");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdIsNull() {
			addCriterion("website_id is null");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdIsNotNull() {
			addCriterion("website_id is not null");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdEqualTo(Integer value) {
			addCriterion("website_id =", value, "websiteId");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdNotEqualTo(Integer value) {
			addCriterion("website_id <>", value, "websiteId");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdGreaterThan(Integer value) {
			addCriterion("website_id >", value, "websiteId");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("website_id >=", value, "websiteId");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdLessThan(Integer value) {
			addCriterion("website_id <", value, "websiteId");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdLessThanOrEqualTo(Integer value) {
			addCriterion("website_id <=", value, "websiteId");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdIn(List<Integer> values) {
			addCriterion("website_id in", values, "websiteId");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdNotIn(List<Integer> values) {
			addCriterion("website_id not in", values, "websiteId");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdBetween(Integer value1, Integer value2) {
			addCriterion("website_id between", value1, value2, "websiteId");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdNotBetween(Integer value1, Integer value2) {
			addCriterion("website_id not between", value1, value2, "websiteId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table uv_reg_company
	 * @mbggenerated  Thu Sep 25 22:18:07 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uv_reg_company
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 19 10:09:25 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}