package com.uvcrawler.vo;

public class ShouldVisitFilter {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_shouldvisit.id
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_shouldvisit.filtertype
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private Short filtertype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_shouldvisit.filterstring
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private String filterstring;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_shouldvisit.website_id
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	private Integer websiteId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_shouldvisit.id
	 * @return  the value of uv_shouldvisit.id
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_shouldvisit.id
	 * @param id  the value for uv_shouldvisit.id
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_shouldvisit.filtertype
	 * @return  the value of uv_shouldvisit.filtertype
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public Short getFiltertype() {
		return filtertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_shouldvisit.filtertype
	 * @param filtertype  the value for uv_shouldvisit.filtertype
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setFiltertype(Short filtertype) {
		this.filtertype = filtertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_shouldvisit.filterstring
	 * @return  the value of uv_shouldvisit.filterstring
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getFilterstring() {
		return filterstring;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_shouldvisit.filterstring
	 * @param filterstring  the value for uv_shouldvisit.filterstring
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setFilterstring(String filterstring) {
		this.filterstring = filterstring;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_shouldvisit.website_id
	 * @return  the value of uv_shouldvisit.website_id
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public Integer getWebsiteId() {
		return websiteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_shouldvisit.website_id
	 * @param websiteId  the value for uv_shouldvisit.website_id
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setWebsiteId(Integer websiteId) {
		this.websiteId = websiteId;
	}
}