package com.uvcrawler.vo;

import java.util.ArrayList;
import java.util.List;

public class ShouldVisitFilterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uv_shouldvisit
     *
     * @mbggenerated Thu Sep 25 22:18:07 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uv_shouldvisit
     *
     * @mbggenerated Thu Sep 25 22:18:07 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uv_shouldvisit
     *
     * @mbggenerated Thu Sep 25 22:18:07 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uv_shouldvisit
     *
     * @mbggenerated Thu Sep 25 22:18:07 CST 2014
     */
    public ShouldVisitFilterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uv_shouldvisit
     *
     * @mbggenerated Thu Sep 25 22:18:07 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uv_shouldvisit
     *
     * @mbggenerated Thu Sep 25 22:18:07 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uv_shouldvisit
     *
     * @mbggenerated Thu Sep 25 22:18:07 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uv_shouldvisit
     *
     * @mbggenerated Thu Sep 25 22:18:07 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uv_shouldvisit
     *
     * @mbggenerated Thu Sep 25 22:18:07 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uv_shouldvisit
     *
     * @mbggenerated Thu Sep 25 22:18:07 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uv_shouldvisit
     *
     * @mbggenerated Thu Sep 25 22:18:07 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uv_shouldvisit
     *
     * @mbggenerated Thu Sep 25 22:18:07 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uv_shouldvisit
     *
     * @mbggenerated Thu Sep 25 22:18:07 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uv_shouldvisit
     *
     * @mbggenerated Thu Sep 25 22:18:07 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uv_shouldvisit
     *
     * @mbggenerated Thu Sep 25 22:18:07 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFiltertypeIsNull() {
            addCriterion("filtertype is null");
            return (Criteria) this;
        }

        public Criteria andFiltertypeIsNotNull() {
            addCriterion("filtertype is not null");
            return (Criteria) this;
        }

        public Criteria andFiltertypeEqualTo(Short value) {
            addCriterion("filtertype =", value, "filtertype");
            return (Criteria) this;
        }

        public Criteria andFiltertypeNotEqualTo(Short value) {
            addCriterion("filtertype <>", value, "filtertype");
            return (Criteria) this;
        }

        public Criteria andFiltertypeGreaterThan(Short value) {
            addCriterion("filtertype >", value, "filtertype");
            return (Criteria) this;
        }

        public Criteria andFiltertypeGreaterThanOrEqualTo(Short value) {
            addCriterion("filtertype >=", value, "filtertype");
            return (Criteria) this;
        }

        public Criteria andFiltertypeLessThan(Short value) {
            addCriterion("filtertype <", value, "filtertype");
            return (Criteria) this;
        }

        public Criteria andFiltertypeLessThanOrEqualTo(Short value) {
            addCriterion("filtertype <=", value, "filtertype");
            return (Criteria) this;
        }

        public Criteria andFiltertypeIn(List<Short> values) {
            addCriterion("filtertype in", values, "filtertype");
            return (Criteria) this;
        }

        public Criteria andFiltertypeNotIn(List<Short> values) {
            addCriterion("filtertype not in", values, "filtertype");
            return (Criteria) this;
        }

        public Criteria andFiltertypeBetween(Short value1, Short value2) {
            addCriterion("filtertype between", value1, value2, "filtertype");
            return (Criteria) this;
        }

        public Criteria andFiltertypeNotBetween(Short value1, Short value2) {
            addCriterion("filtertype not between", value1, value2, "filtertype");
            return (Criteria) this;
        }

        public Criteria andFilterstringIsNull() {
            addCriterion("filterstring is null");
            return (Criteria) this;
        }

        public Criteria andFilterstringIsNotNull() {
            addCriterion("filterstring is not null");
            return (Criteria) this;
        }

        public Criteria andFilterstringEqualTo(String value) {
            addCriterion("filterstring =", value, "filterstring");
            return (Criteria) this;
        }

        public Criteria andFilterstringNotEqualTo(String value) {
            addCriterion("filterstring <>", value, "filterstring");
            return (Criteria) this;
        }

        public Criteria andFilterstringGreaterThan(String value) {
            addCriterion("filterstring >", value, "filterstring");
            return (Criteria) this;
        }

        public Criteria andFilterstringGreaterThanOrEqualTo(String value) {
            addCriterion("filterstring >=", value, "filterstring");
            return (Criteria) this;
        }

        public Criteria andFilterstringLessThan(String value) {
            addCriterion("filterstring <", value, "filterstring");
            return (Criteria) this;
        }

        public Criteria andFilterstringLessThanOrEqualTo(String value) {
            addCriterion("filterstring <=", value, "filterstring");
            return (Criteria) this;
        }

        public Criteria andFilterstringLike(String value) {
            addCriterion("filterstring like", value, "filterstring");
            return (Criteria) this;
        }

        public Criteria andFilterstringNotLike(String value) {
            addCriterion("filterstring not like", value, "filterstring");
            return (Criteria) this;
        }

        public Criteria andFilterstringIn(List<String> values) {
            addCriterion("filterstring in", values, "filterstring");
            return (Criteria) this;
        }

        public Criteria andFilterstringNotIn(List<String> values) {
            addCriterion("filterstring not in", values, "filterstring");
            return (Criteria) this;
        }

        public Criteria andFilterstringBetween(String value1, String value2) {
            addCriterion("filterstring between", value1, value2, "filterstring");
            return (Criteria) this;
        }

        public Criteria andFilterstringNotBetween(String value1, String value2) {
            addCriterion("filterstring not between", value1, value2, "filterstring");
            return (Criteria) this;
        }

        public Criteria andWebsiteIdIsNull() {
            addCriterion("website_id is null");
            return (Criteria) this;
        }

        public Criteria andWebsiteIdIsNotNull() {
            addCriterion("website_id is not null");
            return (Criteria) this;
        }

        public Criteria andWebsiteIdEqualTo(Integer value) {
            addCriterion("website_id =", value, "websiteId");
            return (Criteria) this;
        }

        public Criteria andWebsiteIdNotEqualTo(Integer value) {
            addCriterion("website_id <>", value, "websiteId");
            return (Criteria) this;
        }

        public Criteria andWebsiteIdGreaterThan(Integer value) {
            addCriterion("website_id >", value, "websiteId");
            return (Criteria) this;
        }

        public Criteria andWebsiteIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("website_id >=", value, "websiteId");
            return (Criteria) this;
        }

        public Criteria andWebsiteIdLessThan(Integer value) {
            addCriterion("website_id <", value, "websiteId");
            return (Criteria) this;
        }

        public Criteria andWebsiteIdLessThanOrEqualTo(Integer value) {
            addCriterion("website_id <=", value, "websiteId");
            return (Criteria) this;
        }

        public Criteria andWebsiteIdIn(List<Integer> values) {
            addCriterion("website_id in", values, "websiteId");
            return (Criteria) this;
        }

        public Criteria andWebsiteIdNotIn(List<Integer> values) {
            addCriterion("website_id not in", values, "websiteId");
            return (Criteria) this;
        }

        public Criteria andWebsiteIdBetween(Integer value1, Integer value2) {
            addCriterion("website_id between", value1, value2, "websiteId");
            return (Criteria) this;
        }

        public Criteria andWebsiteIdNotBetween(Integer value1, Integer value2) {
            addCriterion("website_id not between", value1, value2, "websiteId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uv_shouldvisit
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 25 22:18:07 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uv_shouldvisit
     *
     * @mbggenerated Thu Sep 25 22:18:07 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}