package com.uvcrawler.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WebsiteExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uv_website
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uv_website
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uv_website
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_website
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public WebsiteExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_website
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_website
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_website
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_website
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_website
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_website
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_website
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_website
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_website
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uv_website
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table uv_website
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andHomePageIsNull() {
			addCriterion("home_page is null");
			return (Criteria) this;
		}

		public Criteria andHomePageIsNotNull() {
			addCriterion("home_page is not null");
			return (Criteria) this;
		}

		public Criteria andHomePageEqualTo(String value) {
			addCriterion("home_page =", value, "homePage");
			return (Criteria) this;
		}

		public Criteria andHomePageNotEqualTo(String value) {
			addCriterion("home_page <>", value, "homePage");
			return (Criteria) this;
		}

		public Criteria andHomePageGreaterThan(String value) {
			addCriterion("home_page >", value, "homePage");
			return (Criteria) this;
		}

		public Criteria andHomePageGreaterThanOrEqualTo(String value) {
			addCriterion("home_page >=", value, "homePage");
			return (Criteria) this;
		}

		public Criteria andHomePageLessThan(String value) {
			addCriterion("home_page <", value, "homePage");
			return (Criteria) this;
		}

		public Criteria andHomePageLessThanOrEqualTo(String value) {
			addCriterion("home_page <=", value, "homePage");
			return (Criteria) this;
		}

		public Criteria andHomePageLike(String value) {
			addCriterion("home_page like", value, "homePage");
			return (Criteria) this;
		}

		public Criteria andHomePageNotLike(String value) {
			addCriterion("home_page not like", value, "homePage");
			return (Criteria) this;
		}

		public Criteria andHomePageIn(List<String> values) {
			addCriterion("home_page in", values, "homePage");
			return (Criteria) this;
		}

		public Criteria andHomePageNotIn(List<String> values) {
			addCriterion("home_page not in", values, "homePage");
			return (Criteria) this;
		}

		public Criteria andHomePageBetween(String value1, String value2) {
			addCriterion("home_page between", value1, value2, "homePage");
			return (Criteria) this;
		}

		public Criteria andHomePageNotBetween(String value1, String value2) {
			addCriterion("home_page not between", value1, value2, "homePage");
			return (Criteria) this;
		}

		public Criteria andEnrtyPageIsNull() {
			addCriterion("enrty_page is null");
			return (Criteria) this;
		}

		public Criteria andEnrtyPageIsNotNull() {
			addCriterion("enrty_page is not null");
			return (Criteria) this;
		}

		public Criteria andEnrtyPageEqualTo(String value) {
			addCriterion("enrty_page =", value, "enrtyPage");
			return (Criteria) this;
		}

		public Criteria andEnrtyPageNotEqualTo(String value) {
			addCriterion("enrty_page <>", value, "enrtyPage");
			return (Criteria) this;
		}

		public Criteria andEnrtyPageGreaterThan(String value) {
			addCriterion("enrty_page >", value, "enrtyPage");
			return (Criteria) this;
		}

		public Criteria andEnrtyPageGreaterThanOrEqualTo(String value) {
			addCriterion("enrty_page >=", value, "enrtyPage");
			return (Criteria) this;
		}

		public Criteria andEnrtyPageLessThan(String value) {
			addCriterion("enrty_page <", value, "enrtyPage");
			return (Criteria) this;
		}

		public Criteria andEnrtyPageLessThanOrEqualTo(String value) {
			addCriterion("enrty_page <=", value, "enrtyPage");
			return (Criteria) this;
		}

		public Criteria andEnrtyPageLike(String value) {
			addCriterion("enrty_page like", value, "enrtyPage");
			return (Criteria) this;
		}

		public Criteria andEnrtyPageNotLike(String value) {
			addCriterion("enrty_page not like", value, "enrtyPage");
			return (Criteria) this;
		}

		public Criteria andEnrtyPageIn(List<String> values) {
			addCriterion("enrty_page in", values, "enrtyPage");
			return (Criteria) this;
		}

		public Criteria andEnrtyPageNotIn(List<String> values) {
			addCriterion("enrty_page not in", values, "enrtyPage");
			return (Criteria) this;
		}

		public Criteria andEnrtyPageBetween(String value1, String value2) {
			addCriterion("enrty_page between", value1, value2, "enrtyPage");
			return (Criteria) this;
		}

		public Criteria andEnrtyPageNotBetween(String value1, String value2) {
			addCriterion("enrty_page not between", value1, value2, "enrtyPage");
			return (Criteria) this;
		}

		public Criteria andAimpageRegIsNull() {
			addCriterion("aimpage_reg is null");
			return (Criteria) this;
		}

		public Criteria andAimpageRegIsNotNull() {
			addCriterion("aimpage_reg is not null");
			return (Criteria) this;
		}

		public Criteria andAimpageRegEqualTo(String value) {
			addCriterion("aimpage_reg =", value, "aimpageReg");
			return (Criteria) this;
		}

		public Criteria andAimpageRegNotEqualTo(String value) {
			addCriterion("aimpage_reg <>", value, "aimpageReg");
			return (Criteria) this;
		}

		public Criteria andAimpageRegGreaterThan(String value) {
			addCriterion("aimpage_reg >", value, "aimpageReg");
			return (Criteria) this;
		}

		public Criteria andAimpageRegGreaterThanOrEqualTo(String value) {
			addCriterion("aimpage_reg >=", value, "aimpageReg");
			return (Criteria) this;
		}

		public Criteria andAimpageRegLessThan(String value) {
			addCriterion("aimpage_reg <", value, "aimpageReg");
			return (Criteria) this;
		}

		public Criteria andAimpageRegLessThanOrEqualTo(String value) {
			addCriterion("aimpage_reg <=", value, "aimpageReg");
			return (Criteria) this;
		}

		public Criteria andAimpageRegLike(String value) {
			addCriterion("aimpage_reg like", value, "aimpageReg");
			return (Criteria) this;
		}

		public Criteria andAimpageRegNotLike(String value) {
			addCriterion("aimpage_reg not like", value, "aimpageReg");
			return (Criteria) this;
		}

		public Criteria andAimpageRegIn(List<String> values) {
			addCriterion("aimpage_reg in", values, "aimpageReg");
			return (Criteria) this;
		}

		public Criteria andAimpageRegNotIn(List<String> values) {
			addCriterion("aimpage_reg not in", values, "aimpageReg");
			return (Criteria) this;
		}

		public Criteria andAimpageRegBetween(String value1, String value2) {
			addCriterion("aimpage_reg between", value1, value2, "aimpageReg");
			return (Criteria) this;
		}

		public Criteria andAimpageRegNotBetween(String value1, String value2) {
			addCriterion("aimpage_reg not between", value1, value2,
					"aimpageReg");
			return (Criteria) this;
		}

		public Criteria andEnabledIsNull() {
			addCriterion("enabled is null");
			return (Criteria) this;
		}

		public Criteria andEnabledIsNotNull() {
			addCriterion("enabled is not null");
			return (Criteria) this;
		}

		public Criteria andEnabledEqualTo(Byte value) {
			addCriterion("enabled =", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledNotEqualTo(Byte value) {
			addCriterion("enabled <>", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledGreaterThan(Byte value) {
			addCriterion("enabled >", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledGreaterThanOrEqualTo(Byte value) {
			addCriterion("enabled >=", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledLessThan(Byte value) {
			addCriterion("enabled <", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledLessThanOrEqualTo(Byte value) {
			addCriterion("enabled <=", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledIn(List<Byte> values) {
			addCriterion("enabled in", values, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledNotIn(List<Byte> values) {
			addCriterion("enabled not in", values, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledBetween(Byte value1, Byte value2) {
			addCriterion("enabled between", value1, value2, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledNotBetween(Byte value1, Byte value2) {
			addCriterion("enabled not between", value1, value2, "enabled");
			return (Criteria) this;
		}

		public Criteria andUseproxyIsNull() {
			addCriterion("useproxy is null");
			return (Criteria) this;
		}

		public Criteria andUseproxyIsNotNull() {
			addCriterion("useproxy is not null");
			return (Criteria) this;
		}

		public Criteria andUseproxyEqualTo(Byte value) {
			addCriterion("useproxy =", value, "useproxy");
			return (Criteria) this;
		}

		public Criteria andUseproxyNotEqualTo(Byte value) {
			addCriterion("useproxy <>", value, "useproxy");
			return (Criteria) this;
		}

		public Criteria andUseproxyGreaterThan(Byte value) {
			addCriterion("useproxy >", value, "useproxy");
			return (Criteria) this;
		}

		public Criteria andUseproxyGreaterThanOrEqualTo(Byte value) {
			addCriterion("useproxy >=", value, "useproxy");
			return (Criteria) this;
		}

		public Criteria andUseproxyLessThan(Byte value) {
			addCriterion("useproxy <", value, "useproxy");
			return (Criteria) this;
		}

		public Criteria andUseproxyLessThanOrEqualTo(Byte value) {
			addCriterion("useproxy <=", value, "useproxy");
			return (Criteria) this;
		}

		public Criteria andUseproxyIn(List<Byte> values) {
			addCriterion("useproxy in", values, "useproxy");
			return (Criteria) this;
		}

		public Criteria andUseproxyNotIn(List<Byte> values) {
			addCriterion("useproxy not in", values, "useproxy");
			return (Criteria) this;
		}

		public Criteria andUseproxyBetween(Byte value1, Byte value2) {
			addCriterion("useproxy between", value1, value2, "useproxy");
			return (Criteria) this;
		}

		public Criteria andUseproxyNotBetween(Byte value1, Byte value2) {
			addCriterion("useproxy not between", value1, value2, "useproxy");
			return (Criteria) this;
		}

		public Criteria andNewdateIsNull() {
			addCriterion("newdate is null");
			return (Criteria) this;
		}

		public Criteria andNewdateIsNotNull() {
			addCriterion("newdate is not null");
			return (Criteria) this;
		}

		public Criteria andNewdateEqualTo(Date value) {
			addCriterion("newdate =", value, "newdate");
			return (Criteria) this;
		}

		public Criteria andNewdateNotEqualTo(Date value) {
			addCriterion("newdate <>", value, "newdate");
			return (Criteria) this;
		}

		public Criteria andNewdateGreaterThan(Date value) {
			addCriterion("newdate >", value, "newdate");
			return (Criteria) this;
		}

		public Criteria andNewdateGreaterThanOrEqualTo(Date value) {
			addCriterion("newdate >=", value, "newdate");
			return (Criteria) this;
		}

		public Criteria andNewdateLessThan(Date value) {
			addCriterion("newdate <", value, "newdate");
			return (Criteria) this;
		}

		public Criteria andNewdateLessThanOrEqualTo(Date value) {
			addCriterion("newdate <=", value, "newdate");
			return (Criteria) this;
		}

		public Criteria andNewdateIn(List<Date> values) {
			addCriterion("newdate in", values, "newdate");
			return (Criteria) this;
		}

		public Criteria andNewdateNotIn(List<Date> values) {
			addCriterion("newdate not in", values, "newdate");
			return (Criteria) this;
		}

		public Criteria andNewdateBetween(Date value1, Date value2) {
			addCriterion("newdate between", value1, value2, "newdate");
			return (Criteria) this;
		}

		public Criteria andNewdateNotBetween(Date value1, Date value2) {
			addCriterion("newdate not between", value1, value2, "newdate");
			return (Criteria) this;
		}

		public Criteria andDomainIsNull() {
			addCriterion("domain is null");
			return (Criteria) this;
		}

		public Criteria andDomainIsNotNull() {
			addCriterion("domain is not null");
			return (Criteria) this;
		}

		public Criteria andDomainEqualTo(String value) {
			addCriterion("domain =", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainNotEqualTo(String value) {
			addCriterion("domain <>", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainGreaterThan(String value) {
			addCriterion("domain >", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainGreaterThanOrEqualTo(String value) {
			addCriterion("domain >=", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainLessThan(String value) {
			addCriterion("domain <", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainLessThanOrEqualTo(String value) {
			addCriterion("domain <=", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainLike(String value) {
			addCriterion("domain like", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainNotLike(String value) {
			addCriterion("domain not like", value, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainIn(List<String> values) {
			addCriterion("domain in", values, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainNotIn(List<String> values) {
			addCriterion("domain not in", values, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainBetween(String value1, String value2) {
			addCriterion("domain between", value1, value2, "domain");
			return (Criteria) this;
		}

		public Criteria andDomainNotBetween(String value1, String value2) {
			addCriterion("domain not between", value1, value2, "domain");
			return (Criteria) this;
		}

		public Criteria andRateIsNull() {
			addCriterion("rate is null");
			return (Criteria) this;
		}

		public Criteria andRateIsNotNull() {
			addCriterion("rate is not null");
			return (Criteria) this;
		}

		public Criteria andRateEqualTo(Integer value) {
			addCriterion("rate =", value, "rate");
			return (Criteria) this;
		}

		public Criteria andRateNotEqualTo(Integer value) {
			addCriterion("rate <>", value, "rate");
			return (Criteria) this;
		}

		public Criteria andRateGreaterThan(Integer value) {
			addCriterion("rate >", value, "rate");
			return (Criteria) this;
		}

		public Criteria andRateGreaterThanOrEqualTo(Integer value) {
			addCriterion("rate >=", value, "rate");
			return (Criteria) this;
		}

		public Criteria andRateLessThan(Integer value) {
			addCriterion("rate <", value, "rate");
			return (Criteria) this;
		}

		public Criteria andRateLessThanOrEqualTo(Integer value) {
			addCriterion("rate <=", value, "rate");
			return (Criteria) this;
		}

		public Criteria andRateIn(List<Integer> values) {
			addCriterion("rate in", values, "rate");
			return (Criteria) this;
		}

		public Criteria andRateNotIn(List<Integer> values) {
			addCriterion("rate not in", values, "rate");
			return (Criteria) this;
		}

		public Criteria andRateBetween(Integer value1, Integer value2) {
			addCriterion("rate between", value1, value2, "rate");
			return (Criteria) this;
		}

		public Criteria andRateNotBetween(Integer value1, Integer value2) {
			addCriterion("rate not between", value1, value2, "rate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table uv_website
	 * @mbggenerated  Fri Sep 26 09:48:36 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uv_website
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 19 10:09:25 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}
