package com.uvcrawler.vo;

import java.util.Date;

public class Website {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_website.id
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_website.name
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_website.home_page
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String homePage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_website.enrty_page
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String enrtyPage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_website.aimpage_reg
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String aimpageReg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_website.enabled
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private Byte enabled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_website.useproxy
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private Byte useproxy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_website.newdate
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private Date newdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_website.domain
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private String domain;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uv_website.rate
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	private Integer rate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_website.id
	 * @return  the value of uv_website.id
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_website.id
	 * @param id  the value for uv_website.id
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_website.name
	 * @return  the value of uv_website.name
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_website.name
	 * @param name  the value for uv_website.name
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_website.home_page
	 * @return  the value of uv_website.home_page
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getHomePage() {
		return homePage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_website.home_page
	 * @param homePage  the value for uv_website.home_page
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setHomePage(String homePage) {
		this.homePage = homePage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_website.enrty_page
	 * @return  the value of uv_website.enrty_page
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getEnrtyPage() {
		return enrtyPage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_website.enrty_page
	 * @param enrtyPage  the value for uv_website.enrty_page
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setEnrtyPage(String enrtyPage) {
		this.enrtyPage = enrtyPage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_website.aimpage_reg
	 * @return  the value of uv_website.aimpage_reg
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getAimpageReg() {
		return aimpageReg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_website.aimpage_reg
	 * @param aimpageReg  the value for uv_website.aimpage_reg
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setAimpageReg(String aimpageReg) {
		this.aimpageReg = aimpageReg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_website.enabled
	 * @return  the value of uv_website.enabled
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public Byte getEnabled() {
		return enabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_website.enabled
	 * @param enabled  the value for uv_website.enabled
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setEnabled(Byte enabled) {
		this.enabled = enabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_website.useproxy
	 * @return  the value of uv_website.useproxy
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public Byte getUseproxy() {
		return useproxy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_website.useproxy
	 * @param useproxy  the value for uv_website.useproxy
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setUseproxy(Byte useproxy) {
		this.useproxy = useproxy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_website.newdate
	 * @return  the value of uv_website.newdate
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public Date getNewdate() {
		return newdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_website.newdate
	 * @param newdate  the value for uv_website.newdate
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setNewdate(Date newdate) {
		this.newdate = newdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_website.domain
	 * @return  the value of uv_website.domain
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public String getDomain() {
		return domain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_website.domain
	 * @param domain  the value for uv_website.domain
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setDomain(String domain) {
		this.domain = domain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uv_website.rate
	 * @return  the value of uv_website.rate
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public Integer getRate() {
		return rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uv_website.rate
	 * @param rate  the value for uv_website.rate
	 * @mbggenerated  Fri Sep 26 15:31:39 CST 2014
	 */
	public void setRate(Integer rate) {
		this.rate = rate;
	}
}
